const $=selector=>document.querySelector(selector);
const slug='game-loop-engine';
const learnerId=(()=>{const key='godot-forge-learner-id';let value=localStorage.getItem(key);if(!value){value=crypto.randomUUID().replace(/-/g,'');localStorage.setItem(key,value);}return value;})();
const copy={
  en:{title:'Game Loop Architecture · Godot Forge',back:'← GODOT FORGE / LEARNING PATH',chapter:'CHAPTER 08 / GAME LOOP ARCHITECTURE',language:'Language',gameStageAria:'Playable coin quest platform game',eyebrow:'CORE GAME SYSTEMS / PHASER DEMO',pageTitle:'Build a complete game loop.',intro:'Collect 20 coins, then touch the glowing grove relic at the end of the path. Celebrate the level clear and continue to restart.',learningEyebrow:'THREE PARTS OF A PLAYABLE LOOP',learningTitle:'Input becomes a finished level',inputStep:'01 / INPUT',inputTitle:'Read player intent',inputCopy:'Keyboard input turns into movement and jumps during each frame.',stateStep:'02 / SIMULATION & STATE',stateTitle:'Update the world',stateCopy:'Physics resolves movement while coin pickups update the quest state.',renderStep:'03 / RENDER & TRANSITION',renderTitle:'Reach the level clear',renderCopy:'The goal checks quest conditions, displays a win state, and starts a fresh level on Continue.',promptEyebrow:'REUSABLE GAME-LOOP PROMPT',promptHeading:'Make the objective and state transitions explicit',promptIntro:'This prompt describes the lesson’s input, simulation, quest state, win condition, and restart flow in the selected language.',promptTitle:'Coin quest and level completion',copyPrompt:'COPY PROMPT',demoEyebrow:'PLAYABLE GAME LOOP',demoTitle:'The Grove Relic Quest',restart:'RESTART LEVEL',quest:'GROVE COINS',goal:'COLLECT 20 · TOUCH THE RELIC',controls:'MOVE · A/D OR ←/→   JUMP / DOUBLE JUMP · W / ↑ / SPACE',levelEyebrow:'QUEST COMPLETE',levelTitle:'Level completed!',levelCopy:'You collected all 20 coins and reached the Grove Relic.',continue:'CONTINUE · RESTART LEVEL',completion:'Collect all 20 coins, then touch the relic to complete the module.',saved:'Module progress saved.',saveError:'Level complete, but progress could not be saved.',needCoins:'Collect all 20 coins before touching the relic.',ready:'Quest complete! Your progress is saved.',copied:'Game-loop prompt copied.',copyError:'Could not copy the prompt.'},
  zh:{title:'游戏循环架构 · Godot Forge',back:'← GODOT FORGE / 学习路径',chapter:'第 08 章 / 游戏循环架构',language:'语言',gameStageAria:'可游玩的金币任务平台游戏',eyebrow:'核心游戏系统 / PHASER 演示',pageTitle:'构建完整的游戏循环。',intro:'收集 20 枚金币，然后触碰路径尽头发光的森林遗物。庆祝关卡完成，并点击继续重新开始。',learningEyebrow:'可玩循环的三个组成部分',learningTitle:'从玩家输入到关卡完成',inputStep:'01 / 输入',inputTitle:'读取玩家意图',inputCopy:'每一帧都会将键盘输入转换为移动和跳跃。',stateStep:'02 / 模拟与状态',stateTitle:'更新游戏世界',stateCopy:'物理系统处理移动，金币拾取则更新任务状态。',renderStep:'03 / 渲染与切换',renderTitle:'完成关卡',renderCopy:'目标检测任务条件、显示胜利状态，并在点击继续后开始新关卡。',promptEyebrow:'可复用的游戏循环提示词',promptHeading:'明确目标和状态转换',promptIntro:'此提示词会以所选语言说明输入、模拟、任务状态、胜利条件和重新开始流程。',promptTitle:'金币任务与关卡完成',copyPrompt:'复制提示词',demoEyebrow:'可游玩的游戏循环',demoTitle:'森林遗物任务',restart:'重新开始关卡',quest:'森林金币',goal:'收集 20 枚 · 触碰遗物',controls:'移动 · A/D 或 ←/→　跳跃 / 二段跳 · W / ↑ / 空格',levelEyebrow:'任务完成',levelTitle:'关卡完成！',levelCopy:'你已收集全部 20 枚金币并抵达森林遗物。',continue:'继续 · 重新开始关卡',completion:'收集全部 20 枚金币，然后触碰遗物即可完成本模块。',saved:'模块进度已保存。',saveError:'关卡已完成，但无法保存进度。',needCoins:'触碰遗物前，请先收集全部 20 枚金币。',ready:'任务完成！进度已保存。',copied:'游戏循环提示词已复制。',copyError:'无法复制提示词。'},
  ms:{title:'Seni Bina Gelung Permainan · Godot Forge',back:'← GODOT FORGE / LALUAN PEMBELAJARAN',chapter:'BAB 08 / SENI BINA GELUNG PERMAINAN',language:'Bahasa',gameStageAria:'Permainan pelantar misi syiling yang boleh dimainkan',eyebrow:'SISTEM TERAS PERMAINAN / DEMO PHASER',pageTitle:'Bina gelung permainan yang lengkap.',intro:'Kutip 20 syiling, kemudian sentuh relik rimba bercahaya di hujung laluan. Raikan tamat aras dan tekan teruskan untuk bermula semula.',learningEyebrow:'TIGA BAHAGIAN GELUNG BOLEH DIMAINKAN',learningTitle:'Input menjadi aras yang lengkap',inputStep:'01 / INPUT',inputTitle:'Baca tindakan pemain',inputCopy:'Input papan kekunci menjadi pergerakan dan lompatan pada setiap bingkai.',stateStep:'02 / SIMULASI & KEADAAN',stateTitle:'Kemas kini dunia',stateCopy:'Fizik mengurus pergerakan manakala kutipan syiling mengemas kini keadaan misi.',renderStep:'03 / PAPARAN & PERALIHAN',renderTitle:'Selesaikan aras',renderCopy:'Matlamat menyemak syarat misi, memaparkan keadaan menang dan memulakan aras baharu apabila Teruskan ditekan.',promptEyebrow:'PROM GELUNG PERMAINAN BOLEH GUNA SEMULA',promptHeading:'Jelaskan objektif dan peralihan keadaan',promptIntro:'Prom ini menerangkan input, simulasi, keadaan misi, syarat menang dan aliran mula semula dalam bahasa yang dipilih.',promptTitle:'Misi syiling dan tamat aras',copyPrompt:'SALIN PROM',demoEyebrow:'GELUNG PERMAINAN BOLEH DIMAINKAN',demoTitle:'Misi Relik Rimba',restart:'MULA SEMULA ARAS',quest:'SYILING RIMBA',goal:'KUTIP 20 · SENTUH RELIK',controls:'GERAK · A/D ATAU ←/→   LOMPAT / LOMPAT BERGANDA · W / ↑ / SPACE',levelEyebrow:'MISI SELESAI',levelTitle:'Aras selesai!',levelCopy:'Anda telah mengutip semua 20 syiling dan sampai ke Relik Rimba.',continue:'TERUSKAN · MULA SEMULA ARAS',completion:'Kutip semua 20 syiling, kemudian sentuh relik untuk melengkapkan modul.',saved:'Kemajuan modul disimpan.',saveError:'Aras selesai, tetapi kemajuan tidak dapat disimpan.',needCoins:'Kutip semua 20 syiling sebelum menyentuh relik.',ready:'Misi selesai! Kemajuan anda disimpan.',copied:'Prom gelung permainan disalin.',copyError:'Prom tidak dapat disalin.'}
};
const prompt={
  en:'Build a Phaser 2D platformer level with a clear game loop: read left/right and jump input, simulate gravity and collisions, update a quest counter when the player collects coins, and render the updated scene each frame. The objective is to collect 20 coins and touch the Grove Relic at the level end. Do not allow the goal to complete early. On success, pause gameplay, show a celebratory “Level completed!” overlay with fireworks, save module completion, and offer a Continue button that resets the player, coins, quest state, and level for replay. Keep input, simulation, game state, rendering, and level transitions in separate, readable functions.',
  zh:'使用 Phaser 构建 2D 平台游戏关卡，并实现清晰的游戏循环：读取左右移动和跳跃输入，模拟重力与碰撞，玩家收集金币时更新任务计数器，并在每一帧渲染更新后的场景。任务目标是在关卡终点收集 20 枚金币并触碰森林遗物。未达成条件时不可提前通关。成功后暂停游戏，显示带烟花效果的“关卡完成！”庆祝界面，保存模块完成状态，并提供“继续”按钮，以便重置玩家、金币、任务状态和关卡供玩家重玩。将输入、模拟、游戏状态、渲染和关卡切换分别写成清晰易读的函数。',
  ms:'Bina aras platformer 2D menggunakan Phaser dengan gelung permainan yang jelas: baca input kiri/kanan dan lompat, simulasikan graviti serta perlanggaran, kemas kini pembilang misi apabila pemain mengutip syiling, dan paparkan adegan terkini pada setiap bingkai. Objektifnya ialah mengutip 20 syiling dan menyentuh Relik Rimba di hujung aras. Jangan benarkan aras selesai sebelum syarat dipenuhi. Selepas berjaya, jeda permainan, paparkan mesej “Aras selesai!” yang diraikan dengan bunga api, simpan status penyelesaian modul dan sediakan butang Teruskan untuk menetapkan semula pemain, syiling, keadaan misi dan aras bagi permainan semula. Asingkan input, simulasi, keadaan permainan, paparan dan peralihan aras dalam fungsi yang jelas.'
};
let locale=localStorage.getItem('godot-forge-locale')||'en';if(!copy[locale])locale='en';
let game,scene,player,coinsGroup,goalSensor,cursors,keys,coinCount=0,levelComplete=false,learnerCompleted=false,jumpsUsed=0,goalWarningShown=false;
const WIDTH=960,HEIGHT=576,WORLD_WIDTH=2400,FLOOR_Y=510,GOAL_X=2260,REQUIRED_COINS=20;
const t=()=>copy[locale];
function applyCopy(){const c=t();document.title=c.title;document.documentElement.lang=locale==='zh'?'zh-CN':locale;document.querySelectorAll('[data-locale]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.locale===locale)));for(const [id,key] of Object.entries({'back-link':'back','chapter-label':'chapter','intro-eyebrow':'eyebrow','page-title':'pageTitle','intro-copy':'intro','learning-eyebrow':'learningEyebrow','learning-title':'learningTitle','input-step':'inputStep','input-title':'inputTitle','input-copy':'inputCopy','state-step':'stateStep','state-title':'stateTitle','state-copy':'stateCopy','render-step':'renderStep','render-title':'renderTitle','render-copy':'renderCopy','prompt-eyebrow':'promptEyebrow','prompt-heading':'promptHeading','prompt-intro':'promptIntro','prompt-title':'promptTitle','copy-prompt':'copyPrompt','demo-eyebrow':'demoEyebrow','demo-title':'demoTitle','restart-demo':'restart','quest-label':'quest','goal-hint':'goal','control-hint':'controls','level-eyebrow':'levelEyebrow','level-title':'levelTitle','level-copy':'levelCopy','continue-button':'continue','completion-status':'completion'})){const el=$(`#${id}`);if(el)el.textContent=c[key];}if(goalWarningShown)$('#goal-hint').textContent=c.needCoins;$('#game-prompt').textContent=prompt[locale];$('#languages').setAttribute('aria-label',c.language);$('#game-stage').setAttribute('aria-label',c.gameStageAria);}
function preload(){this.load.setCORS('anonymous');this.load.image('forest-far','https://godot-forge.sgp1.digitaloceanspaces.com/2d-game-development/parallax-tiling-map/images/parallax-far.webp');this.load.image('forest-mid','https://godot-forge.sgp1.digitaloceanspaces.com/2d-game-development/parallax-tiling-map/images/parallax-midground.webp');this.load.spritesheet('hero','https://godot-forge.sgp1.digitaloceanspaces.com/2d-game-development/items-spawning/images/forest-sword-explorer.png',{frameWidth:256,frameHeight:256});this.load.spritesheet('hud-icons','https://godot-forge.sgp1.digitaloceanspaces.com/2d-game-development/game-settings/images/forest-hud-icons.png',{frameWidth:256,frameHeight:256});}
function makeAnims(){const a=this.anims;a.create({key:'loop-idle',frames:a.generateFrameNumbers('hero',{start:0,end:0}),frameRate:5,repeat:-1});a.create({key:'loop-walk',frames:a.generateFrameNumbers('hero',{start:16,end:23}),frameRate:10,repeat:-1});a.create({key:'loop-jump',frames:a.generateFrameNumbers('hero',{start:32,end:35}),frameRate:12,repeat:0});}
function create(){
  scene=this;this.physics.world.setBounds(0,0,WORLD_WIDTH,HEIGHT);this.cameras.main.setBounds(0,0,WORLD_WIDTH,HEIGHT).setBackgroundColor('#17332a');
  this.add.tileSprite(0,0,WORLD_WIDTH,HEIGHT,'forest-far').setOrigin(0).setScrollFactor(.12).setDepth(-10).setTint(0xd5e6db);
  this.add.tileSprite(0,90,WORLD_WIDTH,HEIGHT-90,'forest-mid').setOrigin(0).setScrollFactor(.32).setDepth(-5).setAlpha(.66);
  const ground=this.add.graphics();ground.fillStyle(0x263f2d).fillRect(0,FLOOR_Y,WORLD_WIDTH,HEIGHT-FLOOR_Y);ground.fillStyle(0x78a84a).fillRect(0,FLOOR_Y,WORLD_WIDTH,9);ground.fillStyle(0x3b5c35);for(let x=0;x<WORLD_WIDTH;x+=64)ground.fillRoundedRect(x+6,FLOOR_Y+22,38,8,3);
  const floor=this.add.rectangle(WORLD_WIDTH/2,FLOOR_Y+48,WORLD_WIDTH,96,0,0);this.physics.add.existing(floor,true);floor.setVisible(false);
  makeAnims.call(this);player=this.physics.add.sprite(100,FLOOR_Y,'hero',0).setScale(.34).setOrigin(.5,.94).setDepth(8).setCollideWorldBounds(true);player.body.setSize(140,200).setOffset(58,35);this.physics.add.collider(player,floor);
  coinsGroup=this.physics.add.group({allowGravity:false,immovable:true});
  for(let index=0;index<REQUIRED_COINS;index++){const x=220+index*95,y=index%4===2?FLOOR_Y-88:FLOOR_Y-36;const coin=coinsGroup.create(x,y,'hud-icons',4).setDisplaySize(31,31).setDepth(6);coin.body.setAllowGravity(false).setImmovable(true);this.tweens.add({targets:coin,y:y-7,duration:510,yoyo:true,repeat:-1,ease:'Sine.easeInOut'});}
  this.physics.add.overlap(player,coinsGroup,collectCoin,null,this);
  const gateY=FLOOR_Y-58,gateArt=this.add.graphics().setDepth(5);gateArt.fillStyle(0x91e791,.12);gateArt.fillCircle(GOAL_X,gateY,49);gateArt.lineStyle(7,0x9def93,.92);gateArt.strokeCircle(GOAL_X,gateY,37);gateArt.lineStyle(2,0xdbffd0,.92);gateArt.strokeCircle(GOAL_X,gateY,25);
  const gateCore=this.add.circle(GOAL_X,gateY,13,0xc4f265,.92).setDepth(5);this.tweens.add({targets:gateCore,scale:1.35,alpha:.55,duration:820,yoyo:true,repeat:-1,ease:'Sine.easeInOut'});
  this.add.text(GOAL_X,FLOOR_Y-115,'GROVE RELIC',{fontFamily:'ui-monospace,monospace',fontSize:'12px',fontStyle:'bold',color:'#ecffd9',stroke:'#102019',strokeThickness:4}).setOrigin(.5).setDepth(7);
  goalSensor=this.add.rectangle(GOAL_X,FLOOR_Y-49,78,105,0,0);this.physics.add.existing(goalSensor,true);this.physics.add.overlap(player,goalSensor,checkGoal,null,this);
  cursors=this.input.keyboard.createCursorKeys();keys=this.input.keyboard.addKeys('A,D,W');this.cameras.main.startFollow(player,true,.1,.08);this.cameras.main.setDeadzone(260,100);
}
function collectCoin(_player,coin){if(!coin.active||levelComplete)return;coin.destroy();coinCount=Math.min(REQUIRED_COINS,coinCount+1);$('#coin-progress').textContent=`${coinCount} / ${REQUIRED_COINS}`;if(coinCount===REQUIRED_COINS){goalWarningShown=false;$('#goal-hint').textContent=t().goal;}}
function checkGoal(){if(levelComplete)return;if(coinCount<REQUIRED_COINS){if(!goalWarningShown){goalWarningShown=true;$('#goal-hint').textContent=t().needCoins;}return;}finishLevel();}
function launchFirework(){const colors=[0xc4f265,0xffd66b,0x9c8cff,0x6fe4c5,0xff806e],width=scene.scale.width;const x=Phaser.Math.Between(90,Math.max(100,width-90)),y=Phaser.Math.Between(75,210),color=Phaser.Utils.Array.GetRandom(colors);for(let index=0;index<22;index++){const angle=index/22*Math.PI*2,radius=Phaser.Math.Between(60,125),spark=scene.add.circle(x,y,Phaser.Math.Between(2,4),color,1).setScrollFactor(0).setDepth(30);scene.tweens.add({targets:spark,x:x+Math.cos(angle)*radius,y:y+Math.sin(angle)*radius,alpha:0,scale:.1,duration:Phaser.Math.Between(650,1100),ease:'Cubic.easeOut',onComplete:()=>spark.destroy()});}}
function finishLevel(){if(levelComplete)return;levelComplete=true;player.setVelocity(0,0);player.anims.play('loop-idle');scene.physics.world.pause();$('#level-overlay').hidden=false;$('#continue-button').focus();$('#completion-status').textContent=t().ready;$('#module-status').textContent='';launchFirework();for(let count=1;count<8;count++)scene.time.delayedCall(count*600,launchFirework);fetch(`/api/modules/${slug}/progress`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({learnerId,completed:true})}).then(response=>{if(!response.ok)throw new Error('save failed');learnerCompleted=true;$('#module-status').textContent=t().saved;}).catch(()=>{$('#module-status').textContent=t().saveError;});}
function update(){if(!player||levelComplete)return;if(goalWarningShown&&!Phaser.Geom.Intersects.RectangleToRectangle(player.getBounds(),goalSensor.getBounds())){goalWarningShown=false;$('#goal-hint').textContent=t().goal;}const left=cursors.left.isDown||keys.A.isDown,right=cursors.right.isDown||keys.D.isDown,jump=Phaser.Input.Keyboard.JustDown(cursors.up)||Phaser.Input.Keyboard.JustDown(cursors.space)||Phaser.Input.Keyboard.JustDown(keys.W),grounded=player.body.blocked.down||player.body.touching.down;if(grounded)jumpsUsed=0;player.setVelocityX(left?-220:right?220:0);if(jump&&(grounded||jumpsUsed<2)){player.setVelocityY(jumpsUsed===0?-470:-420);jumpsUsed+=1;}if(left)player.setFlipX(true);else if(right)player.setFlipX(false);if(!grounded)player.anims.play('loop-jump',true);else if(left||right)player.anims.play('loop-walk',true);else player.anims.play('loop-idle',true);}
function initGame(){if(game){game.destroy(true);game=null;}scene=null;player=null;coinsGroup=null;goalSensor=null;coinCount=0;jumpsUsed=0;goalWarningShown=false;levelComplete=false;$('#coin-progress').textContent=`0 / ${REQUIRED_COINS}`;$('#goal-hint').textContent=t().goal;$('#level-overlay').hidden=true;$('#module-status').textContent='';game=new Phaser.Game({type:Phaser.AUTO,parent:'game-stage',width:WIDTH,height:HEIGHT,backgroundColor:'#17332a',physics:{default:'arcade',arcade:{gravity:{y:1120},debug:false}},scene:{preload,create,update},scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH}});}
document.querySelectorAll('[data-locale]').forEach(button=>button.addEventListener('click',()=>{const next=button.dataset.locale;if(!copy[next])return;locale=next;localStorage.setItem('godot-forge-locale',locale);applyCopy();}));
$('#restart-demo').addEventListener('click',()=>{initGame();window.showToast?.(t().restart,'success');});
$('#continue-button').addEventListener('click',()=>{initGame();window.showToast?.(t().restart,'success');$('#restart-demo').focus();});
$('#copy-prompt').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(prompt[locale]);window.showToast?.(t().copied,'success');}catch{window.showToast?.(t().copyError,'error');}});
window.addEventListener('godot-forge-module-reset',event=>{if(event.detail?.slug===slug)initGame();});
applyCopy();initGame();
