const slug = 'enemies-ai';
const learnerId = (() => { const key = 'godot-forge-learner-id'; let value = localStorage.getItem(key); if (!value) { value = crypto.randomUUID().replace(/-/g, ''); localStorage.setItem(key, value); } return value; })();
const $ = selector => document.querySelector(selector);
const copy = {
  en: {
    title:'Enemies & AI · Godot Forge', back:'← GODOT FORGE / LEARNING PATH', chapter:'CHAPTER 07 / ENEMIES & AI', eyebrow:'GAMEPLAY AI / PHASER DEMO', pageTitle:'Teach enemies to notice and pursue the player.', intro:'Approach the forest enemies to trigger their awareness. The Mossback Boar charges when you get close; the Thornling darts after you. Watch their state labels, then use your sword to make space.', learningEyebrow:'THREE CORE IDEAS', learningTitle:'What this system teaches', senseStep:'01 / PERCEPTION', senseTitle:'Notice the player', senseCopy:'A detection radius and vertical check decide when a nearby player is visible to an enemy.', stateStep:'02 / STATE MACHINE', stateTitle:'Patrol, chase, recover', stateCopy:'Enemy state changes select movement, facing, and animation without mixing their rules.', combatStep:'03 / COMBAT FEEDBACK', combatTitle:'Attack with a readable tell', combatCopy:'Close-range attack timing, player health, hit reactions, and cooldowns make danger legible.', promptsEyebrow:'AI ART DIRECTION / REUSABLE PROMPTS', promptsTitle:'Two enemies, one forest style', promptsIntro:'Review or copy the prompts used to generate these animation sheets. Prompts are available in English, Chinese, and Malay.', boarTitle:'Mossback Boar · wild boar', thornlingTitle:'Thornling · root creature', badge:'GPT IMAGE 2.5 SUNBURST / ASSET PROMPT', copyPrompt:'COPY PROMPT', demoEyebrow:'PLAYABLE ENEMY AI DEMO', demoTitle:'Trigger the chase', restart:'RESTART DEMO', playerHealth:n=>`PLAYER · ${'♥'.repeat(n)}${'♡'.repeat(3-n)}`, boarLabel:'MOSSBACK BOAR', thornlingLabel:'THORNLING', patrol:'PATROL', chase:'CHASE', attackState:'ATTACK', recover:'RECOVER', defeated:'DEFEATED', objective:'Move close to both enemies to trigger their chase, then hit each with your sword.', move:'MOVE · A/D OR ←/→', jump:'JUMP · W / ↑ / SPACE', attack:'SWORD ATTACK · J / X NEAR AN ENEMY', completion:'Trigger both enemy chases and land a sword hit on each to finish this module.', complete:'COMPLETE MODULE', completed:'MODULE COMPLETE ✓', ready:'Both enemies pursued you, and you landed a sword hit on each.', saved:'Enemies & AI progress saved.', saveError:'Could not save module progress. Please try again.', reset:'Demo restarted.', tooFar:'Move closer and face an enemy to strike.', hit:'Sword hit!', playerHit:'An enemy hit you!', defeatedToast:'Enemy defeated. Watch it recover and return.', copied:'Enemy prompt copied.', copyError:'Could not copy the prompt.'
  },
  zh: {
    title:'敌人与 AI · Godot Forge', back:'← GODOT FORGE / 学习路径', chapter:'第 07 章 / 敌人与 AI', eyebrow:'游戏 AI / PHASER 演示', pageTitle:'让敌人发现并追逐玩家。', intro:'靠近森林敌人以触发警觉。苔背野猪会在你接近时冲锋，荆棘灵会快速追来。观察它们的状态标签，再挥剑拉开距离。', learningEyebrow:'三个核心概念', learningTitle:'本系统的学习内容', senseStep:'01 / 感知', senseTitle:'发现玩家', senseCopy:'敌人通过侦测范围和垂直距离判断附近玩家是否可见。', stateStep:'02 / 状态机', stateTitle:'巡逻、追逐、恢复', stateCopy:'敌人状态分别控制移动、朝向和动画，避免规则互相干扰。', combatStep:'03 / 战斗反馈', combatTitle:'清晰可读的攻击提示', combatCopy:'近距离攻击时机、玩家生命值、受击反馈和冷却时间让危险更容易判断。', promptsEyebrow:'AI 美术设定 / 可复用提示词', promptsTitle:'两种敌人，同一森林风格', promptsIntro:'查看或复制用于生成这些动画素材表的提示词。提示词提供英文、中文和马来文版本。', boarTitle:'苔背野猪 · 野猪敌人', thornlingTitle:'荆棘灵 · 树根生物', badge:'GPT IMAGE 2.5 SUNBURST / 素材提示词', copyPrompt:'复制提示词', demoEyebrow:'可游玩的敌人 AI 演示', demoTitle:'触发追逐行为', restart:'重新开始演示', playerHealth:n=>`玩家 · ${'♥'.repeat(n)}${'♡'.repeat(3-n)}`, boarLabel:'苔背野猪', thornlingLabel:'荆棘灵', patrol:'巡逻', chase:'追逐', attackState:'攻击', recover:'恢复', defeated:'已击败', objective:'靠近两种敌人触发追逐，然后分别用剑击中它们。', move:'移动 · A/D 或 ←/→', jump:'跳跃 · W / ↑ / 空格', attack:'挥剑攻击 · 靠近敌人时按 J / X', completion:'触发两种敌人的追逐，并分别用剑击中它们即可完成模块。', complete:'完成模块', completed:'模块已完成 ✓', ready:'两种敌人都追逐了你，而且你都用剑击中了它们。', saved:'敌人与 AI 进度已保存。', saveError:'无法保存模块进度，请重试。', reset:'演示已重新开始。', tooFar:'请靠近敌人并面向它再攻击。', hit:'挥剑命中！', playerHit:'你被敌人击中了！', defeatedToast:'敌人已击败。留意它恢复并返回。', copied:'敌人提示词已复制。', copyError:'无法复制提示词。'
  },
  ms: {
    title:'Musuh & AI · Godot Forge', back:'← GODOT FORGE / LALUAN PEMBELAJARAN', chapter:'BAB 07 / MUSUH & AI', eyebrow:'AI PERMAINAN / DEMO PHASER', pageTitle:'Ajar musuh mengesan dan mengejar pemain.', intro:'Dekati musuh hutan untuk mencetuskan kesedaran mereka. Babi Hutan Lumut akan menyerbu apabila anda menghampiri; Thornling akan meluru mengejar. Perhatikan label keadaan mereka, kemudian gunakan pedang untuk menjauhkan mereka.', learningEyebrow:'TIGA IDEA UTAMA', learningTitle:'Perkara yang dipelajari', senseStep:'01 / PERSEPSI', senseTitle:'Mengesan pemain', senseCopy:'Jejari pengesanan dan semakan jarak menegak menentukan bila pemain berdekatan kelihatan kepada musuh.', stateStep:'02 / MESIN KEADAAN', stateTitle:'Ronda, kejar, pulih', stateCopy:'Perubahan keadaan musuh memilih pergerakan, arah hadapan dan animasi tanpa mencampuradukkan peraturannya.', combatStep:'03 / MAKLUM BALAS PERTARUNGAN', combatTitle:'Serangan dengan petunjuk jelas', combatCopy:'Masa serangan dekat, nyawa pemain, reaksi terkena dan masa bertenang menjadikan bahaya mudah difahami.', promptsEyebrow:'ARAHAN SENI AI / PROM BOLEH GUNA SEMULA', promptsTitle:'Dua musuh, satu gaya hutan', promptsIntro:'Lihat atau salin prom yang digunakan untuk menjana helaian animasi ini. Prom tersedia dalam bahasa Inggeris, Cina dan Melayu.', boarTitle:'Babi Hutan Lumut · babi hutan', thornlingTitle:'Thornling · makhluk akar', badge:'GPT IMAGE 2.5 SUNBURST / PROM ASET', copyPrompt:'SALIN PROM', demoEyebrow:'DEMO AI MUSUH BOLEH DIMAINKAN', demoTitle:'Cetuskankan kejaran', restart:'MULA SEMULA DEMO', playerHealth:n=>`PEMAIN · ${'♥'.repeat(n)}${'♡'.repeat(3-n)}`, boarLabel:'BABI HUTAN LUMUT', thornlingLabel:'THORNLING', patrol:'RONDA', chase:'KEJAR', attackState:'SERANG', recover:'PULIH', defeated:'TEWAS', objective:'Dekati kedua-dua musuh untuk mencetuskan kejaran, kemudian pukul setiap satu dengan pedang.', move:'GERAK · A/D ATAU ←/→', jump:'LOMPAT · W / ↑ / SPACE', attack:'SERANG PEDANG · J / X BERHAMPIRAN MUSUH', completion:'Cetuskankan kejaran kedua-dua musuh dan pukul setiap satu dengan pedang untuk melengkapkan modul ini.', complete:'LENGKAPKAN MODUL', completed:'MODUL SELESAI ✓', ready:'Kedua-dua musuh mengejar anda dan anda berjaya memukul setiap satu dengan pedang.', saved:'Kemajuan Musuh & AI disimpan.', saveError:'Kemajuan modul tidak dapat disimpan. Sila cuba lagi.', reset:'Demo dimulakan semula.', tooFar:'Dekati musuh dan halakan watak ke arahnya untuk menyerang.', hit:'Pedang mengenai sasaran!', playerHit:'Anda terkena serangan musuh!', defeatedToast:'Musuh ditewaskan. Perhatikan ia pulih dan kembali.', copied:'Prom musuh disalin.', copyError:'Prom tidak dapat disalin.'
  }
};

const assetPrompts = {
  en: {
    boar:'Use GPT Image 2.5 Sunburst to create a transparent-background 2D pixel-art enemy sprite sheet for a side-view forest platformer. Mossback Boar: a powerful stocky wild boar with dark umber fur, layered moss-and-leaf armor, pale curved tusks, amber eyes, and a luminous lime leaf marking. Exact 4 columns × 4 rows, sixteen equal 256×256 cells, one complete boar per cell, facing right, consistent scale, baseline, and silhouette. Row 1: four idle/breathing poses. Row 2: four distinct grounded patrol walking poses with alternating legs. Row 3: four energetic forward-leaning charge/run poses with pumping legs. Row 4: four close-range attack poses: anticipation, tusk strike, follow-through, recovery. Fill every cell and keep the full boar inside each with transparent padding. Crisp hand-crafted pixel clusters, forest-green highlights, teal shadows, earthy brown body. True transparent alpha; no scenery, floor, text, labels, borders, grid lines, watermark, extra creatures, cropping, isometric view, or top-down view.',
    thornling:'Use GPT Image 2.5 Sunburst to create a transparent-background 2D pixel-art enemy sprite sheet for the same side-view forest platformer and visual style as the Mossback Boar. Thornling: a smaller nimble bipedal forest creature made of twisted roots and bark, leafy crest, glowing amber eyes, moss patches, and one curled thorn-vine arm. Clearly distinct upright narrow silhouette, facing right. Exact 4 columns × 4 rows, sixteen equal 256×256 cells, one complete creature per cell, consistent scale, baseline, and proportions. Row 1: four idle poses. Row 2: four distinct patrol walk poses with alternating feet. Row 3: four quick springing chase/run poses leaning forward. Row 4: four readable close-range vine-swipe attack poses: anticipation, strike, follow-through, recovery. Fill every cell; preserve the entire body and vine with transparent margins. Crisp polished pixel clusters, matching forest greens, teal shadows, warm amber accents. True transparent alpha; no scenery, floor, text, labels, borders, grid lines, watermark, extra creatures, cropped parts, isometric view, or top-down view.'
  },
  zh: {
    boar:'使用 GPT Image 2.5 Sunburst，为侧视角森林平台游戏制作透明背景的 2D 像素风敌人动画素材表。苔背野猪：强壮结实的野猪，深棕色皮毛、层叠苔藓与树叶护甲、浅色弯獠牙、琥珀色眼睛和发光亮绿色叶片纹饰。严格采用 4 列 × 4 行，共十六个 256×256 等大格子；每格一只完整野猪，面朝右方，比例、基线和轮廓一致。第一行：四个待机／呼吸姿势。第二行：四个双腿交替、脚步贴地的巡逻行走姿势。第三行：四个身体前倾、腿部有力摆动的冲锋／奔跑姿势。第四行：四个近距离攻击姿势，依次为蓄势、獠牙冲击、攻击延续和恢复。填满所有格子；每格完整呈现野猪并保留透明边距。手工像素块精致清晰，森林绿高光、蓝绿色阴影和棕色身体。使用真正透明 Alpha；不要场景、地面、文字、标签、边框、网格线、水印、额外生物、裁切、等距视角或俯视角。',
    thornling:'使用 GPT Image 2.5 Sunburst，为与苔背野猪属于同一美术风格的侧视角森林平台游戏制作透明背景的 2D 像素风敌人动画素材表。荆棘灵：体型较小、动作敏捷的双足森林生物，由扭曲树根与树皮构成，头顶叶冠、琥珀色发光眼睛、苔藓斑块和一只卷曲的荆棘藤手臂。轮廓直立而纤细，明显区别于野猪，面朝右方。严格采用 4 列 × 4 行，共十六个 256×256 等大格子；每格一只完整生物，比例、基线和姿态一致。第一行：四个待机姿势。第二行：四个双脚交替的巡逻行走姿势。第三行：四个向前倾斜、弹跳追逐的快速奔跑姿势。第四行：四个清晰的近距离藤蔓挥击动作，依次为蓄势、挥击、动作延续和恢复。填满每格；完整呈现身体和藤蔓并留透明边距。像素块精致清晰，配色与森林绿、蓝绿色阴影和暖琥珀色点缀保持一致。使用真正透明 Alpha；不要场景、地面、文字、标签、边框、网格线、水印、额外生物、裁切部分、等距视角或俯视角。'
  },
  ms: {
    boar:'Gunakan GPT Image 2.5 Sunburst untuk menghasilkan helaian sprite musuh seni piksel 2D berlatar lutsinar bagi permainan platform hutan pandangan sisi. Babi Hutan Lumut: babi hutan sasa dengan bulu perang gelap, perisai lumut dan daun berlapis, gading melengkung pucat, mata ambar dan tanda daun hijau limau bercahaya. Susun tepat dalam 4 lajur × 4 baris, enam belas sel sama besar 256×256; satu babi hutan lengkap bagi setiap sel, menghadap ke kanan dengan skala, garis dasar dan siluet konsisten. Baris 1: empat pose pegun/bernafas. Baris 2: empat pose rondaan berjalan yang menapak dengan kaki berselang-seli. Baris 3: empat pose serbu/berlari yang condong ke hadapan dengan kaki bergerak kuat. Baris 4: empat pose serangan dekat: bersedia, serangan gading, susulan dan pulih. Penuhi setiap sel dan pastikan seluruh babi hutan muat dengan ruang lutsinar. Kelompok piksel buatan tangan yang kemas, sorotan hijau hutan, bayang teal dan badan perang tanah. Alpha lutsinar sebenar; tanpa pemandangan, tanah, teks, label, sempadan, garisan grid, tera air, makhluk tambahan, potongan, perspektif isometrik atau pandangan atas.',
    thornling:'Gunakan GPT Image 2.5 Sunburst untuk menghasilkan helaian sprite musuh seni piksel 2D berlatar lutsinar bagi permainan platform hutan pandangan sisi, dengan gaya sama seperti Babi Hutan Lumut. Thornling: makhluk hutan kecil dan lincah berkaki dua, terbina daripada akar berpintal dan kulit kayu, berjambul daun, bermata ambar bercahaya, bertompok lumut dan mempunyai satu lengan sulur berduri yang melingkar. Siluet tegak yang ramping dan jelas berbeza daripada babi hutan, menghadap ke kanan. Susun tepat dalam 4 lajur × 4 baris, enam belas sel sama besar 256×256; satu makhluk lengkap setiap sel dengan skala, garis dasar dan perkadaran konsisten. Baris 1: empat pose pegun. Baris 2: empat pose rondaan berjalan dengan kaki berselang-seli. Baris 3: empat pose kejaran pantas yang melompat dan condong ke hadapan. Baris 4: empat pose serangan hayunan sulur dekat: bersedia, hayun, susulan dan pulih. Penuhi setiap sel; kekalkan seluruh badan dan sulur dengan ruang lutsinar. Kelompok piksel kemas dengan hijau hutan, bayang teal dan aksen ambar hangat yang sepadan. Alpha lutsinar sebenar; tanpa pemandangan, tanah, teks, label, sempadan, garisan grid, tera air, makhluk tambahan, bahagian terpotong, perspektif isometrik atau pandangan atas.'
  }
};

let locale = ['zh','ms'].includes(localStorage.getItem('godot-forge-locale')) ? localStorage.getItem('godot-forge-locale') : 'en';
let game, scene, player, cursors, keys, enemies = [], health = 3, invulnerableUntil = 0, playerAttackUntil = 0, attackAt = 0, playerFacing = 1, completed = false, completionReady = false;
const WIDTH = 960, HEIGHT = 576, WORLD_WIDTH = 1920, FLOOR_Y = 516;
const enemyDefinitions = [
  { id:'boar', name:'Mossback Boar', key:'boar', asset:'https://godot-forge.sgp1.digitaloceanspaces.com/2d-game-development/enemies-ai/images/mossback-boar.png', x:610, scale:.55, groundOriginY:.862, aggro:330, loseAggro:485, speed:112, attackRange:66, attackCooldown:1500, hp:3, patrol:[450,780] },
  { id:'thornling', name:'Thornling', key:'thornling', asset:'https://godot-forge.sgp1.digitaloceanspaces.com/2d-game-development/enemies-ai/images/thornling.png', x:1000, scale:.53, aggro:260, loseAggro:410, speed:145, attackRange:58, attackCooldown:1800, hp:2, patrol:[830,1210] }
];

function stateName(mode){const c=copy[locale];return ({patrol:c.patrol,chase:c.chase,attack:c.attackState,recover:c.recover,defeated:c.defeated})[mode]||c.patrol;}
function updateHud(){if(!$('#player-health'))return;$('#player-health').textContent=copy[locale].playerHealth(health);for(const enemy of enemies){const label=$(`#${enemy.id}-state`);if(label)label.textContent=`${enemy.uiName} · ${stateName(enemy.mode)}${enemy.alive?` · ${'♥'.repeat(enemy.hp)}`:''}`;}$('#complete-module').disabled=!completionReady||completed;if(completed)$('#complete-module').textContent=copy[locale].completed;}
function updateCompletion(){completionReady=enemies.length===2&&enemies.every(enemy=>enemy.chased&&enemy.hit);if(completionReady)$('#completion-status').textContent=copy[locale].ready;updateHud();}
function applyCopy(){const c=copy[locale];document.title=c.title;document.documentElement.lang=locale==='zh'?'zh-CN':locale;document.querySelectorAll('[data-locale]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.locale===locale)));for(const [id,key] of Object.entries({ 'back-link':'back','chapter-label':'chapter','intro-eyebrow':'eyebrow','page-title':'pageTitle','intro-copy':'intro','learning-eyebrow':'learningEyebrow','learning-title':'learningTitle','sense-step':'senseStep','sense-title':'senseTitle','sense-copy':'senseCopy','state-step':'stateStep','state-title':'stateTitle','state-copy':'stateCopy','combat-step':'combatStep','combat-title':'combatTitle','combat-copy':'combatCopy','prompts-eyebrow':'promptsEyebrow','prompts-title':'promptsTitle','prompts-intro':'promptsIntro','boar-prompt-title':'boarTitle','thornling-prompt-title':'thornlingTitle','demo-eyebrow':'demoEyebrow','demo-title':'demoTitle','restart-demo':'restart','move-help':'move','jump-help':'jump','attack-help':'attack','objective-hint':'objective','completion-status':'completion','complete-module':'complete'})){const el=$(`#${id}`);if(el)el.textContent=c[key];}document.querySelectorAll('.prompt-badge').forEach(el=>el.textContent=c.badge);document.querySelectorAll('[data-copy-prompt]').forEach(el=>el.textContent=c.copyPrompt);$('#boar-prompt').textContent=assetPrompts[locale].boar;$('#thornling-prompt').textContent=assetPrompts[locale].thornling;enemies.forEach(enemy=>{enemy.uiName=enemy.id==='boar'?c.boarLabel:c.thornlingLabel;enemy.label?.setText(enemyLabel(enemy));});updateHud();}
function enemyLabel(enemy){return `${enemy.uiName} · ${stateName(enemy.mode)}${enemy.alive?` · ${'♥'.repeat(enemy.hp)}`:''}`;}
function preload(){this.load.setCORS('anonymous');this.load.image('forest-far','https://godot-forge.sgp1.digitaloceanspaces.com/2d-game-development/parallax-tiling-map/images/parallax-far.webp');this.load.image('forest-mid','https://godot-forge.sgp1.digitaloceanspaces.com/2d-game-development/parallax-tiling-map/images/parallax-midground.webp');this.load.spritesheet('hero','https://godot-forge.sgp1.digitaloceanspaces.com/2d-game-development/items-spawning/images/forest-sword-explorer.png',{frameWidth:256,frameHeight:256});for(const enemy of enemyDefinitions)this.load.spritesheet(enemy.key,enemy.asset,{frameWidth:256,frameHeight:256});}
function makeGround(){const g=this.add.graphics();g.fillStyle(0x263f2d).fillRect(0,FLOOR_Y,WORLD_WIDTH,HEIGHT-FLOOR_Y);g.fillStyle(0x78a84a).fillRect(0,FLOOR_Y,WORLD_WIDTH,9);g.fillStyle(0x3b5c35);for(let x=0;x<WORLD_WIDTH;x+=64)g.fillRoundedRect(x+6,FLOOR_Y+22,38,8,3);}
function makeAnimations(){const a=this.anims;const add=(key,texture,start,end,frameRate,repeat)=>a.create({key,frames:a.generateFrameNumbers(texture,{start,end}),frameRate,repeat});add('hero-idle','hero',0,0,5,-1);add('hero-walk','hero',8,15,9,-1);add('hero-run','hero',16,23,13,-1);add('hero-attack','hero',24,27,12,0);add('hero-jump','hero',32,35,12,0);for(const d of enemyDefinitions){add(`${d.key}-idle`,d.key,0,3,4,-1);add(`${d.key}-patrol`,d.key,4,7,7,-1);add(`${d.key}-chase`,d.key,8,11,11,-1);add(`${d.key}-attack`,d.key,12,15,10,0);}}
function create(){scene=this;this.physics.world.setBounds(0,0,WORLD_WIDTH,HEIGHT);this.cameras.main.setBounds(0,0,WORLD_WIDTH,HEIGHT).setBackgroundColor('#17332a');this.add.tileSprite(0,0,WORLD_WIDTH,HEIGHT,'forest-far').setOrigin(0).setScrollFactor(.12).setDepth(-10).setTint(0xd5e6db);this.add.tileSprite(0,95,WORLD_WIDTH,HEIGHT-95,'forest-mid').setOrigin(0).setScrollFactor(.32).setDepth(-5).setAlpha(.6);makeGround.call(this);makeAnimations.call(this);const floor=this.add.rectangle(WORLD_WIDTH/2,FLOOR_Y+48,WORLD_WIDTH,96,0,0);this.physics.add.existing(floor,true);floor.setVisible(false);player=this.physics.add.sprite(210,FLOOR_Y,'hero',0).setScale(.34).setOrigin(.5,.94).setDepth(8).setCollideWorldBounds(true);player.body.setSize(140,200).setOffset(58,35);this.physics.add.collider(player,floor);enemies=enemyDefinitions.map(d=>{const sprite=this.physics.add.sprite(d.x,FLOOR_Y,d.key,4).setScale(d.scale).setOrigin(.5,d.groundOriginY||.94).setDepth(7).setImmovable(true).setCollideWorldBounds(true);sprite.body.setAllowGravity(false);sprite.body.setSize(150,170).setOffset(53,55);const enemy={...d,sprite,uiName:copy[locale][d.id==='boar'?'boarLabel':'thornlingLabel'],mode:'patrol',direction:1,hp:d.hp,alive:true,chased:false,hit:false,attackUntil:0,nextAttackAt:0,label:this.add.text(d.x,FLOOR_Y-166,'',{fontFamily:'ui-monospace,monospace',fontSize:'10px',fontStyle:'bold',color:'#edf5e9',backgroundColor:'#102019dd',padding:{x:6,y:4}}).setOrigin(.5).setDepth(12)};sprite.play(`${d.key}-patrol`);enemy.label.setText(enemyLabel(enemy));return enemy;});cursors=this.input.keyboard.createCursorKeys();keys=this.input.keyboard.addKeys('A,D,W,J,X');this.cameras.main.startFollow(player,true,.1,.08);this.cameras.main.setDeadzone(260,100);updateHud();}
function damagePlayer(enemy){const now=scene.time.now;if(now<invulnerableUntil)return;invulnerableUntil=now+1050;health=Math.max(0,health-1);player.setTint(0xff8e76);player.setVelocityX(enemy.direction*190);scene.time.delayedCall(180,()=>player?.clearTint());window.showToast?.(copy[locale].playerHit,'error');if(health===0){health=3;scene.time.delayedCall(550,()=>{if(!player?.active)return;player.setPosition(210,FLOOR_Y);player.setVelocity(0,0);player.setTint(0xffffff);});}updateHud();}
function updateEnemy(enemy,now){if(!enemy.sprite.active)return;enemy.label.setPosition(enemy.sprite.x,FLOOR_Y-166);if(!enemy.alive)return;const dx=player.x-enemy.sprite.x,dy=Math.abs(player.y-enemy.sprite.y),distance=Math.abs(dx);if(now<enemy.attackUntil){enemy.mode='attack';enemy.sprite.setVelocityX(0);enemy.sprite.anims.play(`${enemy.key}-attack`,true);return;}const aggroRange=enemy.chased?enemy.loseAggro:enemy.aggro;if(distance<=aggroRange&&dy<115){enemy.chased=true;enemy.direction=dx<0?-1:1;enemy.sprite.setFlipX(enemy.direction<0);if(distance<=enemy.attackRange&&now<enemy.nextAttackAt){enemy.mode='recover';enemy.sprite.setVelocityX(0);enemy.sprite.anims.play(`${enemy.key}-idle`,true);}else if(distance<=enemy.attackRange){enemy.mode='attack';enemy.sprite.setVelocityX(0);enemy.attackUntil=now+440;enemy.nextAttackAt=now+enemy.attackCooldown;enemy.sprite.anims.play(`${enemy.key}-attack`,true);scene.time.delayedCall(230,()=>{if(enemy.alive&&Math.abs(player.x-enemy.sprite.x)<=enemy.attackRange+20)damagePlayer(enemy);});}else{enemy.mode='chase';enemy.sprite.setVelocityX(enemy.direction*enemy.speed);enemy.sprite.anims.play(`${enemy.key}-chase`,true);}}else{enemy.mode='patrol';if(enemy.sprite.x<enemy.patrol[0])enemy.direction=1;if(enemy.sprite.x>enemy.patrol[1])enemy.direction=-1;enemy.sprite.setFlipX(enemy.direction<0);enemy.sprite.setVelocityX(enemy.direction*enemy.speed*.36);enemy.sprite.anims.play(`${enemy.key}-patrol`,true);}enemy.label.setText(enemyLabel(enemy));}
function hitEnemy(enemy){if(!enemy.alive||enemy.hp<=0)return;enemy.hp--;enemy.hit=true;enemy.sprite.setTint(0xffc878);scene.time.delayedCall(140,()=>enemy.sprite?.clearTint());if(enemy.hp===0){enemy.alive=false;enemy.mode='defeated';enemy.sprite.setVelocityX(0);enemy.label.setText(enemyLabel(enemy));scene.tweens.add({targets:enemy.sprite,alpha:0,duration:460,onComplete:()=>scene.time.delayedCall(1250,()=>{if(!enemy.sprite?.active)return;enemy.hp=enemy.maxHp||enemyDefinitions.find(d=>d.id===enemy.id).hp;enemy.alive=true;enemy.mode='patrol';enemy.sprite.setPosition(enemy.x,FLOOR_Y).setAlpha(1).clearTint().setFlipX(false);enemy.sprite.body.reset(enemy.x,FLOOR_Y);enemy.sprite.anims.play(`${enemy.key}-patrol`);enemy.label.setPosition(enemy.x,FLOOR_Y-139).setText(enemyLabel(enemy));updateHud();})});window.showToast?.(copy[locale].defeatedToast,'success');}else window.showToast?.(copy[locale].hit,'success');enemy.label.setText(enemyLabel(enemy));updateCompletion();}
function attackEnemy(){const now=scene.time.now;if(now-attackAt<420)return;attackAt=now;playerAttackUntil=now+360;player.anims.play('hero-attack',true);const target=enemies.filter(e=>e.alive&&Math.abs(e.sprite.x-player.x)<112&&Math.abs(e.sprite.y-player.y)<110&&((e.sprite.x-player.x)*playerFacing)>-10).sort((a,b)=>Math.abs(a.sprite.x-player.x)-Math.abs(b.sprite.x-player.x))[0];if(!target){window.showToast?.(copy[locale].tooFar);return;}target.sprite.setVelocityX(0);hitEnemy(target);}
function update(){if(!player)return;const left=cursors.left.isDown||keys.A.isDown,right=cursors.right.isDown||keys.D.isDown,jump=Phaser.Input.Keyboard.JustDown(cursors.up)||Phaser.Input.Keyboard.JustDown(cursors.space)||Phaser.Input.Keyboard.JustDown(keys.W),grounded=player.body.blocked.down||player.body.touching.down;player.setVelocityX(left?-220:right?220:0);if(left)playerFacing=-1;else if(right)playerFacing=1;if(jump&&grounded)player.setVelocityY(-470);if(Phaser.Input.Keyboard.JustDown(keys.J)||Phaser.Input.Keyboard.JustDown(keys.X))attackEnemy();enemies.forEach(enemy=>updateEnemy(enemy,scene.time.now));player.setFlipX(playerFacing<0);if(scene.time.now<playerAttackUntil)player.anims.play('hero-attack',true);else if(!grounded)player.anims.play('hero-jump',true);else if(left||right)player.anims.play(Math.abs(player.body.velocity.x)>260?'hero-run':'hero-walk',true);else player.anims.play('hero-idle',true);updateCompletion();}
function initGame({preserveCompletion=false}={}){const wasCompleted=completed;if(game){game.destroy(true);game=null;}player=null;enemies=[];health=3;invulnerableUntil=0;playerAttackUntil=0;attackAt=0;playerFacing=1;completionReady=false;completed=preserveCompletion&&wasCompleted;$('#complete-module').textContent=completed?copy[locale].completed:copy[locale].complete;$('#completion-status').textContent=copy[locale].completion;game=new Phaser.Game({type:Phaser.AUTO,parent:'enemy-stage',width:WIDTH,height:HEIGHT,backgroundColor:'#17332a',physics:{default:'arcade',arcade:{gravity:{y:1100},debug:false}},scene:{preload,create,update},scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH}});updateHud();}
async function markCompleted(){if(!completionReady||completed)return;const button=$('#complete-module');button.disabled=true;try{const response=await fetch(`/api/modules/${slug}/progress`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({learnerId,completed:true})});if(!response.ok)throw new Error();completed=true;$('#completion-status').textContent=copy[locale].saved;window.showToast?.(copy[locale].saved,'success');}catch{$('#completion-status').textContent=copy[locale].saveError;window.showToast?.(copy[locale].saveError,'error');}finally{updateHud();}}
$('#languages').addEventListener('click',event=>{const next=event.target.closest('[data-locale]')?.dataset.locale;if(!copy[next])return;locale=next;localStorage.setItem('godot-forge-locale',locale);applyCopy();});
$('#restart-demo').addEventListener('click',()=>{initGame({preserveCompletion:true});window.showToast?.(copy[locale].reset,'success');});
$('#complete-module').addEventListener('click',markCompleted);
document.querySelectorAll('[data-copy-prompt]').forEach(button=>button.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(assetPrompts[locale][button.dataset.copyPrompt]);window.showToast?.(copy[locale].copied,'success');}catch{window.showToast?.(copy[locale].copyError,'error');}}));
window.addEventListener('godot-forge-module-reset',event=>{if(event.detail?.slug===slug){completed=false;initGame();}});
applyCopy();
initGame();
fetch(`/api/modules?learnerId=${encodeURIComponent(learnerId)}`).then(response=>response.json()).then(modules=>{completed=Boolean(modules.find(module=>module.slug===slug)?.completed);updateHud();}).catch(()=>{});
