const slug='game-settings';
const learnerId=(()=>{const key='godot-forge-learner-id';let value=localStorage.getItem(key);if(!value){value=crypto.randomUUID().replace(/-/g,'');localStorage.setItem(key,value);}return value;})();
const $=selector=>document.querySelector(selector);
const copy={
  en:{title:'Game HUD and Settings · Godot Forge',back:'← GODOT FORGE / LEARNING PATH',chapter:'CHAPTER 10 / GAME HUD & SETTINGS',eyebrow:'PLAYER FEEDBACK / PHASER DEMO',pageTitle:'Make the important information easy to read.',intro:'Keep player health visible on the left and collected coins on the right. Press Escape to pause and open settings, then control music and sound effects independently.',learningEyebrow:'THREE CORE IDEAS',learningTitle:'What this system teaches',healthStep:'01 / PLAYER STATUS',healthTitle:'Health at a glance',healthCopy:'A persistent left-side health bar makes damage visible without blocking the play area.',currencyStep:'02 / GAME PROGRESS',currencyTitle:'Track collected coins',currencyCopy:'A right-aligned counter updates as the player collects world coins.',settingsStep:'03 / PLAYER OPTIONS',settingsTitle:'Pause and adjust audio',settingsCopy:'Escape pauses the game and opens settings with independent music and sound controls.',promptEyebrow:'AI ART DIRECTION / REUSABLE PROMPT',promptHeading:'HUD icons in the game’s visual style',promptIntro:'These icons were generated with GPT Image 2.5 Sunburst as a transparent 4 × 4 sheet. Copy the prompt to create a matching set.',promptTitle:'Forest HUD audio settings icon sheet',copyPrompt:'COPY PROMPT',demoEyebrow:'PLAYABLE HUD & SETTINGS DEMO',demoTitle:'Explore the forest',restart:'RESTART DEMO',healthLabel:'PLAYER HEALTH',coinLabel:'COINS',escapeCopy:'SETTINGS',settingsEyebrow:'PAUSED / PLAYER OPTIONS',settingsTitle:'Game settings',settingsDescription:'Choose which game audio you want to hear.',music:'Music',musicDescription:'Background game music',sound:'Sound effects',soundDescription:'Jump and coin sounds',on:'ON',off:'OFF',settingsFootnote:'Your choices are saved on this device.',resume:'RESUME GAME',move:'MOVE · A/D OR ←/→',jump:'JUMP / DOUBLE JUMP · W / ↑ / SPACE',collect:'COLLECT · WALK INTO COINS',settingsHelp:'PAUSE / SETTINGS · ESC',completion:'Collect a coin, take a little damage, and use both audio settings to complete the module.',complete:'COMPLETE MODULE',completed:'MODULE COMPLETE ✓',ready:'You collected a coin, saw the health bar update, and changed both audio options.',saved:'Game HUD and Settings progress saved.',saveError:'Could not save module progress. Please try again.',reset:'Demo restarted.',coinCollected:'Coin collected!',hurt:'The thorns took some health.',copied:'HUD art prompt copied.',copyError:'Could not copy the prompt.'},
zh:{title:'游戏 HUD 与设置 · Godot Forge',back:'← GODOT FORGE / 学习路径',chapter:'第 10 章 / 游戏 HUD 与设置',eyebrow:'玩家反馈 / PHASER 演示',pageTitle:'让重要信息一目了然。',intro:'在左侧显示玩家生命值，在右侧显示已收集的金币。按 Escape 暂停并打开设置，然后分别控制背景音乐和音效。',learningEyebrow:'三个核心概念',learningTitle:'本系统的学习内容',healthStep:'01 / 玩家状态',healthTitle:'快速查看生命值',healthCopy:'固定在左侧的生命条能清楚显示受到的伤害，同时避免遮挡主要游戏区域。',currencyStep:'02 / 游戏进度',currencyTitle:'追踪已收集金币',currencyCopy:'玩家收集场景中的金币时，右侧计数器会同步更新。',settingsStep:'03 / 玩家选项',settingsTitle:'暂停并调整音频',settingsCopy:'按 Escape 暂停游戏并打开设置，背景音乐和音效可分别开关。',promptEyebrow:'AI 美术设定 / 可复用提示词',promptHeading:'符合游戏视觉风格的 HUD 图标',promptIntro:'这些图标由 GPT Image 2.5 Sunburst 生成，采用透明背景的 4 × 4 素材表。复制提示词即可创建配套图标。',promptTitle:'森林 HUD 与音频设置图标素材表',copyPrompt:'复制提示词',demoEyebrow:'可游玩的 HUD 与设置演示',demoTitle:'探索森林',restart:'重新开始演示',healthLabel:'玩家生命值',coinLabel:'金币',escapeCopy:'设置',settingsEyebrow:'已暂停 / 玩家选项',settingsTitle:'游戏设置',settingsDescription:'选择你想听到的游戏音频。',music:'背景音乐',musicDescription:'游戏背景音乐',sound:'音效',soundDescription:'跳跃与金币音效',on:'开启',off:'关闭',settingsFootnote:'选择会保存在此设备上。',resume:'继续游戏',move:'移动 · A/D 或 ←/→',jump:'跳跃 / 二段跳 · W / ↑ / 空格',collect:'收集 · 接触金币',settingsHelp:'暂停 / 设置 · ESC',completion:'收集一枚金币、受到少量伤害，并切换两项音频设置即可完成模块。',complete:'完成模块',completed:'模块已完成 ✓',ready:'你已收集金币、看到生命条变化，并修改两项音频设置。',saved:'游戏 HUD 与设置进度已保存。',saveError:'无法保存模块进度，请重试。',reset:'演示已重新开始。',coinCollected:'已收集金币！',hurt:'荆棘使生命值下降。',copied:'HUD 美术提示词已复制。',copyError:'无法复制提示词。'},
  ms:{title:'HUD dan Tetapan Permainan · Godot Forge',back:'← GODOT FORGE / LALUAN PEMBELAJARAN',chapter:'BAB 10 / HUD & TETAPAN PERMAINAN',eyebrow:'MAKLUM BALAS PEMAIN / DEMO PHASER',pageTitle:'Jadikan maklumat penting mudah dibaca.',intro:'Paparkan nyawa pemain di sebelah kiri dan jumlah syiling di sebelah kanan. Tekan Escape untuk menjeda permainan dan membuka tetapan, kemudian kawal muzik dan kesan bunyi secara berasingan.',learningEyebrow:'TIGA IDEA UTAMA',learningTitle:'Perkara yang dipelajari',healthStep:'01 / STATUS PEMAIN',healthTitle:'Lihat nyawa sepintas lalu',healthCopy:'Bar nyawa tetap di sebelah kiri menunjukkan kerosakan tanpa menutup kawasan permainan.',currencyStep:'02 / KEMAJUAN PERMAINAN',currencyTitle:'Jejak syiling yang dikutip',currencyCopy:'Pembilang di sebelah kanan dikemas kini apabila pemain mengutip syiling di dunia.',settingsStep:'03 / PILIHAN PEMAIN',settingsTitle:'Jeda dan laraskan audio',settingsCopy:'Escape menjeda permainan dan membuka tetapan dengan kawalan muzik dan bunyi yang berasingan.',promptEyebrow:'ARAHAN SENI AI / PROM BOLEH GUNA SEMULA',promptHeading:'Ikon HUD yang sepadan dengan gaya permainan',promptIntro:'Ikon ini dijana menggunakan GPT Image 2.5 Sunburst sebagai helaian 4 × 4 berlatar lutsinar. Salin prom untuk menghasilkan set yang sepadan.',promptTitle:'Helaian ikon HUD dan tetapan audio hutan',copyPrompt:'SALIN PROM',demoEyebrow:'DEMO HUD & TETAPAN BOLEH DIMAINKAN',demoTitle:'Teroka hutan',restart:'MULA SEMULA DEMO',healthLabel:'NYAWA PEMAIN',coinLabel:'SYILING',escapeCopy:'TETAPAN',settingsEyebrow:'DIJEDA / PILIHAN PEMAIN',settingsTitle:'Tetapan permainan',settingsDescription:'Pilih audio permainan yang ingin didengar.',music:'Muzik',musicDescription:'Muzik latar permainan',sound:'Kesan bunyi',soundDescription:'Bunyi lompat dan syiling',on:'HIDUP',off:'MATI',settingsFootnote:'Pilihan anda disimpan pada peranti ini.',resume:'SAMBUNG PERMAINAN',move:'GERAK · A/D ATAU ←/→',jump:'LOMPAT / LOMPAT BERGANDA · W / ↑ / SPACE',collect:'KUTIP · SENTUH SYILING',settingsHelp:'JEDA / TETAPAN · ESC',completion:'Kutip satu syiling, terima sedikit kerosakan dan ubah kedua-dua tetapan audio untuk melengkapkan modul.',complete:'LENGKAPKAN MODUL',completed:'MODUL SELESAI ✓',ready:'Anda mengutip syiling, melihat bar nyawa berubah dan mengubah kedua-dua pilihan audio.',saved:'Kemajuan HUD dan Tetapan Permainan disimpan.',saveError:'Kemajuan modul tidak dapat disimpan. Sila cuba lagi.',reset:'Demo dimulakan semula.',coinCollected:'Syiling dikutip!',hurt:'Duri mengurangkan nyawa anda.',copied:'Prom seni HUD disalin.',copyError:'Prom tidak dapat disalin.'}
};
const assetPrompt={
  en:'Use GPT Image 2.5 Sunburst to create a transparent-background pixel-art HUD icon sprite sheet for a polished 2D forest platformer. Exact 4 columns × 4 rows, sixteen equal square cells, one centered icon per cell, consistent scale and crisp pixel clusters. Exact row order: row 1: full heart, half heart, empty heart, horizontal health-bar fill segment; row 2: single gold coin, coin stack, coin pouch, sparkling collectible coin; row 3: music note enabled, music note muted with slash, speaker enabled with sound waves, speaker muted with slash; row 4: settings gear, resume/play triangle, restart circular arrow, close X. Match the forest game art with deep teal outlines, forest-green shadows, lime health accents, warm gold currency, and restrained purple highlights. Keep each icon fully within its cell with transparent gutters. True transparent alpha. No background, text, labels, letters, numbers, border, grid lines, watermark, or scenery.',
  zh:'使用 GPT Image 2.5 Sunburst，为精致的 2D 森林平台游戏制作透明背景的像素风 HUD 图标精灵素材表。严格采用 4 列 × 4 行，共十六个等大方格，每格居中放置一个图标，尺寸统一、像素块清晰。严格按以下顺序排列：第一行：完整爱心、半颗爱心、空心爱心、横向生命条填充段；第二行：单枚金币、金币堆、金币袋、闪亮收藏金币；第三行：开启状态的音符、带斜线的静音音符、带声波的开启扬声器、带斜线的静音扬声器；第四行：设置齿轮、继续／播放三角形、循环重启箭头、关闭 X。与森林游戏美术风格一致，使用深蓝绿色轮廓、森林绿阴影、亮绿色生命值、暖金色货币和少量紫色点缀。图标完整放在各自格子中并留透明边距。使用真正透明 Alpha；不要背景、文字、标签、字母、数字、边框、网格线、水印或场景。',
  ms:'Gunakan GPT Image 2.5 Sunburst untuk menghasilkan helaian sprite ikon HUD seni piksel berlatar lutsinar bagi permainan platform hutan 2D yang kemas. Susun tepat dalam 4 lajur × 4 baris, enam belas sel sama besar dengan satu ikon di tengah setiap sel, skala seragam dan kelompok piksel yang jelas. Turutan tepat: baris 1: hati penuh, hati separuh, hati kosong, segmen isi bar nyawa mendatar; baris 2: satu syiling emas, timbunan syiling, uncang syiling, syiling kutipan berkilau; baris 3: not muzik aktif, not muzik senyap dengan garis pangkah, pembesar suara aktif dengan gelombang bunyi, pembesar suara senyap dengan garis pangkah; baris 4: gear tetapan, segi tiga sambung/main, anak panah mula semula, X tutup. Padankan seni permainan hutan dengan garis teal gelap, bayang hijau hutan, aksen nyawa hijau limau, mata wang emas hangat dan sedikit ungu. Pastikan setiap ikon penuh dalam sel dengan ruang lutsinar. Alpha lutsinar sebenar. Tanpa latar, teks, label, huruf, nombor, sempadan, garisan grid, tera air atau pemandangan.'
};
Object.assign(copy.en,{intro:'Keep player health visible on the left and collected coins on the right. At zero health, play the character death animation before respawning. Coins return after five seconds; healing hearts restore 25 HP and return after eight seconds.',healthCopy:'The health bar makes damage clear; reaching zero triggers the character’s death animation and a safe respawn. Heart pickups restore up to 25 HP and return after eight seconds.',currencyCopy:'Coins return after five seconds; healing hearts refill up to 25 HP and return after eight seconds.',collect:'COINS · 5S RETURN / HEARTS · +25 HP / 8S',coinCollected:'Coin collected — it returns in 5 seconds!',heartCollected:'Heart collected — +25 HP; it returns in 8 seconds!'});
Object.assign(copy.zh,{intro:'在左侧显示玩家生命值，在右侧显示已收集的金币。生命值归零时先播放角色死亡动画，再让角色重生。金币会在五秒后重现；治疗爱心可恢复 25 点生命值，并在八秒后重现。',healthCopy:'生命条清晰显示受到的伤害；生命值归零时会播放角色死亡动画并安全重生。爱心道具最多恢复 25 点生命值，并在八秒后重现。',currencyCopy:'金币会在五秒后重现；治疗爱心最多恢复 25 点生命值，并在八秒后重现。',collect:'金币 5 秒重现 · 爱心 +25 点生命值 / 8 秒重现',coinCollected:'已收集金币，5 秒后会重现！',heartCollected:'已收集爱心，恢复 25 点生命值；8 秒后重现！'});
Object.assign(copy.ms,{intro:'Paparkan nyawa pemain di sebelah kiri dan syiling yang dikutip di sebelah kanan. Apabila nyawa habis, mainkan animasi kematian watak sebelum muncul semula. Syiling kembali selepas lima saat; hati memulihkan 25 HP dan kembali selepas lapan saat.',healthCopy:'Bar nyawa menunjukkan kerosakan dengan jelas; apabila habis, animasi kematian dimainkan sebelum watak muncul semula dengan selamat. Hati memulihkan sehingga 25 HP dan kembali selepas lapan saat.',currencyCopy:'Syiling kembali selepas lima saat; hati memulihkan sehingga 25 HP dan muncul semula selepas lapan saat.',collect:'SYILING · KEMBALI 5S / HATI · +25 HP / 8S',coinCollected:'Syiling dikutip — kembali dalam 5 saat!',heartCollected:'Hati dikutip — +25 HP; kembali dalam 8 saat!'});
assetPrompt.en+=' Make the full-heart icon clearly identify a healing pickup worth +25 HP that respawns after eight seconds, while the empty heart communicates depleted health and the death/respawn state; the sparkling coin should read as a returning pickup.';
assetPrompt.zh+=' 完整爱心图标应清楚表示可恢复 25 点生命值、并在八秒后重现的治疗道具；空心爱心表示生命值耗尽及死亡／重生状态；闪亮金币表示会重新出现的拾取物。';
assetPrompt.ms+=' Jadikan ikon hati penuh jelas sebagai item pemulihan +25 HP yang muncul semula selepas lapan saat; hati kosong menunjukkan nyawa habis serta keadaan mati/muncul semula; syiling berkilau menunjukkan item kutipan yang akan kembali.';
let locale=['zh','ms'].includes(localStorage.getItem('godot-forge-locale'))?localStorage.getItem('godot-forge-locale'):'en';
let game,scene,player,coinsGroup,heartsGroup,hazardsGroup,cursors,keys,coins=0,health=100,jumpsUsed=0,playerDead=false,musicEnabled=localStorage.getItem('godot-forge-music')!=='false',soundEnabled=localStorage.getItem('godot-forge-sound')!=='false',settingsOpen=false,menuOpened=false,musicTouched=false,soundTouched=false,damageTaken=false,invulnerableUntil=0,completed=false,completionReady=false,audioContext,musicTimer=null,musicStep=0,musicVoices=new Set();
const WIDTH=960,HEIGHT=576,WORLD_WIDTH=1920,FLOOR_Y=510,MAX_HEALTH=100,MAX_JUMPS=2,HUD_ICONS='https://godot-forge.sgp1.digitaloceanspaces.com/2d-game-development/game-settings/images/forest-hud-icons.png';
const t=()=>copy[locale];

function updateHud(){if(!$('#health-fill'))return;$('#health-fill').style.width=`${health}%`;$('.health-meter').setAttribute('aria-valuenow',String(health));$('.health-meter').dataset.low=String(health<=35);$('#health-value').textContent=`${health}%`;$('#coin-count').textContent=String(coins);$('#complete-module').disabled=!completionReady||completed;if(completed)$('#complete-module').textContent=t().completed;}
function updateCompletion(){completionReady=coins>0&&damageTaken&&menuOpened&&musicTouched&&soundTouched;if(completionReady)$('#completion-status').textContent=t().ready;updateHud();}
function applyCopy(){const c=t();document.title=c.title;document.documentElement.lang=locale==='zh'?'zh-CN':locale;document.querySelectorAll('[data-locale]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.locale===locale)));for(const [id,key] of Object.entries({'back-link':'back','chapter-label':'chapter','intro-eyebrow':'eyebrow','page-title':'pageTitle','intro-copy':'intro','learning-eyebrow':'learningEyebrow','learning-title':'learningTitle','health-step':'healthStep','health-title':'healthTitle','health-copy':'healthCopy','currency-step':'currencyStep','currency-title':'currencyTitle','currency-copy':'currencyCopy','settings-step':'settingsStep','settings-title':'settingsTitle','settings-copy':'settingsCopy','prompt-eyebrow':'promptEyebrow','prompt-heading':'promptHeading','prompt-intro':'promptIntro','prompt-title':'promptTitle','copy-prompt':'copyPrompt','demo-eyebrow':'demoEyebrow','demo-title':'demoTitle','restart-demo':'restart','health-label':'healthLabel','coin-label':'coinLabel','escape-copy':'escapeCopy','settings-eyebrow':'settingsEyebrow','settings-dialog-title':'settingsTitle','settings-description':'settingsDescription','music-label':'music','music-description':'musicDescription','sound-label':'sound','sound-description':'soundDescription','settings-footnote':'settingsFootnote','resume-label':'resume','move-help':'move','jump-help':'jump','collect-help':'collect','settings-help':'settingsHelp','completion-status':'completion','complete-module':'complete'})){const el=$(`#${id}`);if(el)el.textContent=c[key];}$('#asset-prompt').textContent=assetPrompt[locale];updateSettingsUI();updateHud();}
function preload(){this.load.setCORS('anonymous');this.load.image('forest-far','https://godot-forge.sgp1.digitaloceanspaces.com/2d-game-development/parallax-tiling-map/images/parallax-far.webp');this.load.image('forest-mid','https://godot-forge.sgp1.digitaloceanspaces.com/2d-game-development/parallax-tiling-map/images/parallax-midground.webp');this.load.spritesheet('hero','https://godot-forge.sgp1.digitaloceanspaces.com/2d-game-development/items-spawning/images/forest-sword-explorer.png',{frameWidth:256,frameHeight:256});this.load.spritesheet('hud-icons',HUD_ICONS,{frameWidth:256,frameHeight:256});}
function makeGround(){const ground=this.add.graphics();ground.fillStyle(0x263f2d).fillRect(0,FLOOR_Y,WORLD_WIDTH,HEIGHT-FLOOR_Y);ground.fillStyle(0x78a84a).fillRect(0,FLOOR_Y,WORLD_WIDTH,9);ground.fillStyle(0x3b5c35);for(let x=0;x<WORLD_WIDTH;x+=64)ground.fillRoundedRect(x+6,FLOOR_Y+22,38,8,3);}
function makeAnims(){const a=this.anims;const add=(key,start,end,frameRate,repeat)=>a.create({key,frames:a.generateFrameNumbers('hero',{start,end}),frameRate,repeat});add('hero-idle',0,0,5,-1);add('hero-walk',16,23,10,-1);add('hero-run',16,23,13,-1);add('hero-attack',24,27,12,0);add('hero-jump',32,35,12,0);add('hero-death',48,51,8,0);}
function addPlatform(x,top,width,height){const art=this.add.graphics();art.fillStyle(0x3e5e3a).fillRect(x-width/2,top,width,height);art.fillStyle(0x8fbe55).fillRect(x-width/2,top,width,8);art.fillStyle(0x2a412c).fillRect(x-width/2,top+height-6,width,6);const body=this.add.rectangle(x,top+height/2,width,height,0,0);this.physics.add.existing(body,true);this.physics.add.collider(player,body);}
function create(){
  scene=this;
  this.physics.world.setBounds(0,0,WORLD_WIDTH,HEIGHT);
  this.cameras.main.setBounds(0,0,WORLD_WIDTH,HEIGHT).setBackgroundColor('#17332a');
  this.add.tileSprite(0,0,WORLD_WIDTH,HEIGHT,'forest-far').setOrigin(0).setScrollFactor(.12).setDepth(-10).setTint(0xd5e6db);
  this.add.tileSprite(0,95,WORLD_WIDTH,HEIGHT-95,'forest-mid').setOrigin(0).setScrollFactor(.32).setDepth(-5).setAlpha(.6);
  makeGround.call(this);makeAnims.call(this);
  const floor=this.add.rectangle(WORLD_WIDTH/2,FLOOR_Y+48,WORLD_WIDTH,96,0,0);
  this.physics.add.existing(floor,true);floor.setVisible(false);
  player=this.physics.add.sprite(110,FLOOR_Y,'hero',0).setScale(.34).setOrigin(.5,.94).setDepth(8).setCollideWorldBounds(true);
  player.body.setSize(140,200).setOffset(58,35);this.physics.add.collider(player,floor);
  addPlatform.call(this,420,410,188,28);addPlatform.call(this,720,340,174,28);addPlatform.call(this,1080,395,200,28);addPlatform.call(this,1440,330,200,28);
  coinsGroup=this.physics.add.group({allowGravity:false,immovable:true});
  for(const [x,y] of [[280,FLOOR_Y-36],[420,370],[600,FLOOR_Y-36],[720,300],[930,FLOOR_Y-36],[1080,355],[1260,FLOOR_Y-36],[1440,290],[1660,FLOOR_Y-36]])spawnCoin(x,y);
  this.physics.add.overlap(player,coinsGroup,collectCoin,null,this);
  heartsGroup=this.physics.add.group({allowGravity:false,immovable:true});
  for(const [x,y] of [[970,FLOOR_Y-38],[1510,FLOOR_Y-38]])spawnHeart(x,y);
  this.physics.add.overlap(player,heartsGroup,collectHeart,null,this);
  hazardsGroup=this.physics.add.staticGroup();
  const hazardArt=this.add.graphics();
  hazardArt.fillStyle(0xc95b49,1);hazardArt.lineStyle(2,0xffd17a,1);
  for(const x of [820,1288]){
    for(let i=0;i<4;i++){
      const left=x-24+i*12,tip=left+6;
      hazardArt.fillTriangle(left,FLOOR_Y,tip,FLOOR_Y-21,left+12,FLOOR_Y);
      hazardArt.lineBetween(left,FLOOR_Y,left+6,FLOOR_Y-21);
      hazardArt.lineBetween(left+6,FLOOR_Y-21,left+12,FLOOR_Y);
    }
    this.add.circle(x,FLOOR_Y-7,29,0xffc35e,.12).setDepth(4);
    const warning=this.add.text(x,FLOOR_Y-27,'!',{fontFamily:'ui-monospace,monospace',fontSize:'18px',fontStyle:'bold',color:'#fff1c2',stroke:'#682f2d',strokeThickness:4}).setOrigin(.5,1).setDepth(7);
    warning.setData('hazard-warning',true);
    const sensor=this.add.rectangle(x,FLOOR_Y-10,48,22,0,0);
    this.physics.add.existing(sensor,true);hazardsGroup.add(sensor);
  }
  this.physics.add.overlap(player,hazardsGroup,damagePlayer,null,this);
  cursors=this.input.keyboard.createCursorKeys();keys=this.input.keyboard.addKeys('A,D,W');
  this.cameras.main.startFollow(player,true,.1,.08);this.cameras.main.setDeadzone(260,100);
}
function spawnCoin(x,y){
  // create() runs while Phaser marks the scene as CREATING, not RUNNING.
  // The group is already ready here, so checking isActive would suppress every initial coin.
  if(!scene||!coinsGroup)return;
  const coin=coinsGroup.create(x,y,'hud-icons',4).setDisplaySize(31,31).setDepth(6);
  coin.body.setAllowGravity(false).setImmovable(true);coin.setData('homeY',y);
  scene.tweens.add({targets:coin,y:y-7,duration:530,yoyo:true,repeat:-1,ease:'Sine.easeInOut'});
}
function spawnHeart(x,y){
  if(!scene||!heartsGroup)return;
  const heart=heartsGroup.create(x,y,'hud-icons',0).setDisplaySize(31,31).setDepth(6);
  heart.body.setAllowGravity(false).setImmovable(true);heart.setData('homeY',y);
  scene.tweens.add({targets:heart,y:y-7,duration:620,yoyo:true,repeat:-1,ease:'Sine.easeInOut'});
}
function collectCoin(_player,coin){if(!coin.active)return;const x=coin.x,y=coin.getData('homeY')??coin.y;coins++;scene.tweens.killTweensOf(coin);coin.destroy();scene.time.delayedCall(5000,()=>spawnCoin(x,y));playEffect(740,.11);setTimeout(()=>playEffect(990,.12),60);window.showToast?.(t().coinCollected,'success');updateCompletion();}
function collectHeart(_player,heart){if(!heart.active||health>=MAX_HEALTH)return;const x=heart.x,y=heart.getData('homeY')??heart.y;health=Math.min(MAX_HEALTH,health+25);scene.tweens.killTweensOf(heart);heart.destroy();scene.time.delayedCall(8000,()=>spawnHeart(x,y));playEffect(620,.14);setTimeout(()=>playEffect(820,.18),70);window.showToast?.(t().heartCollected,'success');updateHud();}
function damagePlayer(){if(!player||playerDead||scene.time.now<invulnerableUntil)return;invulnerableUntil=scene.time.now+850;health=Math.max(0,health-25);damageTaken=true;player.setTint(0xff806e);player.setVelocityY(-160);scene.time.delayedCall(170,()=>{if(player?.active&&!playerDead)player.clearTint();});if(health===0){playerDead=true;player.setVelocity(0,0);player.body.enable=false;player.clearTint();player.anims.play('hero-death');scene.time.delayedCall(850,()=>{if(!player?.active)return;health=MAX_HEALTH;playerDead=false;player.body.enable=true;const respawnX=Math.max(110,scene.cameras.main.scrollX+100);player.setPosition(Math.min(WORLD_WIDTH-50,respawnX),FLOOR_Y);player.setVelocity(0,0);player.anims.play('hero-idle');jumpsUsed=0;updateHud();});}playEffect(145,.22,'sawtooth');window.showToast?.(t().hurt,'error');updateCompletion();}
function update(){if(!player||playerDead)return;const left=cursors.left.isDown||keys.A.isDown,right=cursors.right.isDown||keys.D.isDown,jump=Phaser.Input.Keyboard.JustDown(cursors.up)||Phaser.Input.Keyboard.JustDown(cursors.space)||Phaser.Input.Keyboard.JustDown(keys.W),grounded=player.body.blocked.down||player.body.touching.down;if(grounded)jumpsUsed=0;player.setVelocityX(left?-220:right?220:0);if(jump&&jumpsUsed<MAX_JUMPS){player.setVelocityY(jumpsUsed===0?-470:-430);jumpsUsed++;playEffect(jumpsUsed===1?390:520,.1);}if(left)player.setFlipX(true);else if(right)player.setFlipX(false);if(!grounded)player.anims.play('hero-jump',true);else if(left||right)player.anims.play('hero-walk',true);else player.anims.play('hero-idle',true);}
function initGame({resetCompletion=false}={}){const wasCompleted=completed;if(game){game.destroy(true);game=null;}player=null;coinsGroup=null;heartsGroup=null;hazardsGroup=null;coins=0;health=MAX_HEALTH;jumpsUsed=0;playerDead=false;invulnerableUntil=0;damageTaken=false;completionReady=false;musicTouched=false;soundTouched=false;menuOpened=false;completed=resetCompletion?false:wasCompleted;$('#complete-module').textContent=completed?t().completed:t().complete;$('#completion-status').textContent=t().completion;$('#settings-overlay').hidden=true;settingsOpen=false;game=new Phaser.Game({type:Phaser.AUTO,parent:'game-stage',width:WIDTH,height:HEIGHT,backgroundColor:'#17332a',physics:{default:'arcade',arcade:{gravity:{y:1120},debug:false}},scene:{preload,create,update},scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH}});updateHud();}
function ensureAudio(){const AudioContextClass=window.AudioContext||window.webkitAudioContext;if(!AudioContextClass)return;if(!audioContext)audioContext=new AudioContextClass();if(audioContext.state==='suspended')audioContext.resume();if(musicEnabled)startMusic();}
function playMusicTone(frequency,duration,volume,waveform='sine',attack=.06){
  const now=audioContext.currentTime,osc=audioContext.createOscillator(),gain=audioContext.createGain();
  osc.type=waveform;osc.frequency.setValueAtTime(frequency,now);
  gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(volume,now+attack);
  gain.gain.setTargetAtTime(.0001,now+duration,Math.max(.04,duration*.12));
  osc.connect(gain);gain.connect(audioContext.destination);musicVoices.add({osc,gain});
  osc.onended=()=>{for(const voice of musicVoices)if(voice.osc===osc)musicVoices.delete(voice);};
  osc.start(now);osc.stop(now+duration+.3);
}
function startMusic(){
  if(!audioContext||musicTimer!==null)return;
  const bars=[
    {root:164.81,chord:[164.81,196,246.94],melody:[392,493.88,587.33,493.88]},
    {root:130.81,chord:[130.81,164.81,196],melody:[329.63,392,493.88,392]},
    {root:196,chord:[146.83,196,246.94],melody:[392,493.88,587.33,659.25]},
    {root:146.83,chord:[146.83,185,220],melody:[369.99,440,493.88,587.33]}
  ];
  musicStep=0;
  const playStep=()=>{
    if(!musicEnabled||!audioContext)return;
    const step=musicStep%32,barIndex=Math.floor(step/8),beat=step%8,bar=bars[barIndex];
    if(beat===0)for(const note of bar.chord)playMusicTone(note,2.65,.014,'sine',.4);
    if(beat%2===0)playMusicTone(bar.root/2, .48,.045,'triangle',.025);
    if(beat===0||beat===2||beat===4||beat===6){
      const phraseIndex=(beat/2+(barIndex%2))%bar.melody.length;
      playMusicTone(bar.melody[phraseIndex],.28,.028,'triangle',.025);
    }
    musicStep++;
  };
  playStep();musicTimer=setInterval(playStep,340);
}
function stopMusic(){if(musicTimer!==null){clearInterval(musicTimer);musicTimer=null;}if(!audioContext)return;const now=audioContext.currentTime;for(const voice of musicVoices){voice.gain.gain.cancelScheduledValues(now);voice.gain.gain.setTargetAtTime(.0001,now,.035);try{voice.osc.stop(now+.16);}catch{}}musicVoices.clear();}
function playEffect(frequency,duration,type='sine'){if(!soundEnabled||!audioContext)return;const now=audioContext.currentTime,osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.type=type;osc.frequency.setValueAtTime(frequency,now);osc.frequency.exponentialRampToValueAtTime(Math.max(60,frequency*.68),now+duration);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.075,now+.012);gain.gain.exponentialRampToValueAtTime(.0001,now+duration);osc.connect(gain);gain.connect(audioContext.destination);osc.start(now);osc.stop(now+duration+.02);}
function updateSettingsUI(){const c=t();$('#music-toggle').setAttribute('aria-pressed',String(musicEnabled));$('#sound-toggle').setAttribute('aria-pressed',String(soundEnabled));$('#music-state').textContent=musicEnabled?c.on:c.off;$('#sound-state').textContent=soundEnabled?c.on:c.off;$('#music-icon').classList.toggle('icon-music-muted',!musicEnabled);$('#music-icon').classList.toggle('icon-music',musicEnabled);$('#sound-icon').classList.toggle('icon-sound-muted',!soundEnabled);$('#sound-icon').classList.toggle('icon-sound',soundEnabled);}
function openSettings(){if(settingsOpen)return;settingsOpen=true;menuOpened=true;$('#settings-overlay').hidden=false;scene?.physics.world.pause();if(scene?.input.keyboard)scene.input.keyboard.enabled=false;ensureAudio();updateSettingsUI();updateCompletion();$('#resume-game').focus();}
function closeSettings(){if(!settingsOpen)return;settingsOpen=false;$('#settings-overlay').hidden=true;scene?.physics.world.resume();if(scene?.input.keyboard)scene.input.keyboard.enabled=true;$('#open-settings').focus();updateCompletion();}
function toggleMusic(){ensureAudio();musicTouched=true;musicEnabled=!musicEnabled;localStorage.setItem('godot-forge-music',String(musicEnabled));if(musicEnabled)startMusic();else stopMusic();updateSettingsUI();updateCompletion();}
function toggleSound(){ensureAudio();soundTouched=true;soundEnabled=!soundEnabled;localStorage.setItem('godot-forge-sound',String(soundEnabled));updateSettingsUI();playEffect(520,.08);updateCompletion();}
async function markCompleted(){if(!completionReady||completed)return;const button=$('#complete-module');button.disabled=true;try{const response=await fetch(`/api/modules/${slug}/progress`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({learnerId,completed:true})});if(!response.ok)throw new Error();completed=true;$('#completion-status').textContent=t().saved;window.showToast?.(t().saved,'success');}catch{$('#completion-status').textContent=t().saveError;window.showToast?.(t().saveError,'error');}finally{updateHud();}}
$('#languages').addEventListener('click',event=>{const next=event.target.closest('[data-locale]')?.dataset.locale;if(!copy[next])return;locale=next;localStorage.setItem('godot-forge-locale',locale);applyCopy();});
$('#open-settings').addEventListener('click',openSettings);
$('#resume-game').addEventListener('click',closeSettings);
$('#music-toggle').addEventListener('click',toggleMusic);
$('#sound-toggle').addEventListener('click',toggleSound);
$('#restart-demo').addEventListener('click',()=>{initGame();window.showToast?.(t().reset,'success');});
$('#complete-module').addEventListener('click',markCompleted);
$('#copy-prompt').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(assetPrompt[locale]);window.showToast?.(t().copied,'success');}catch{window.showToast?.(t().copyError,'error');}});
document.addEventListener('keydown',event=>{if(event.code==='Escape'){event.preventDefault();event.stopImmediatePropagation();if(settingsOpen)closeSettings();else openSettings();return;}ensureAudio();},true);
document.addEventListener('pointerdown',ensureAudio,{passive:true});
window.addEventListener('godot-forge-module-reset',event=>{if(event.detail?.slug===slug){initGame({resetCompletion:true});}});
applyCopy();
initGame();
fetch(`/api/modules?learnerId=${encodeURIComponent(learnerId)}`).then(response=>response.json()).then(modules=>{completed=Boolean(modules.find(module=>module.slug===slug)?.completed);updateHud();}).catch(()=>{});
