const slug='items-spawning';
const learnerId=(()=>{const key='godot-forge-learner-id';let value=localStorage.getItem(key);if(!value){value=crypto.randomUUID().replace(/-/g,'');localStorage.setItem(key,value);}return value;})();
const $=selector=>document.querySelector(selector);
const copy={
  en:{title:'Item Spawning · Godot Forge',back:'← GODOT FORGE / LEARNING PATH',chapter:'CHAPTER 06 / ITEMS & REWARDS',language:'Language',eyebrow:'GAMEPLAY SYSTEMS / PHASER DEMO',pageTitle:'Make the world reward exploration.',intro:'Watch pickups appear at randomized positions, collect them by touching them, then defeat the grove brute to scatter its loot.',learningEyebrow:'THREE CORE IDEAS',learningTitle:'What this system teaches',spawnStep:'01 / SPAWN RULES',collectStep:'02 / COLLECTION',lootStep:'03 / ENEMY DROPS',spawnTitle:'Random world pickups',spawnCopy:'A timer creates pickups ahead of the player while limiting how many can exist at once.',collectTitle:'Contact-based collection',collectCopy:'An overlap check collects an item, removes its sprite, and updates the player’s counters.',lootTitle:'Rewards after combat',lootCopy:'Defeating the grove brute spawns a small random bundle of collectible loot.',demoEyebrow:'PLAYABLE SYSTEM DEMO',demoTitle:'Explore, collect, earn loot',restart:'RESTART DEMO',pickups:n=>`PICKUPS · ${n}`,loot:(collected,total)=>`LOOT · ${collected} / ${total}`,monster:hp=>`GROVE BRUTE · ${'♥'.repeat(hp)}`,defeated:'GROVE BRUTE · DEFEATED',objective:'Collect a glowing item, defeat the monster, then collect its loot.',move:'MOVE · A/D OR ←/→',jump:'JUMP · W / ↑ / SPACE',attack:'SWORD SWING · J / X NEAR MONSTER',completion:'Complete the three demo tasks to finish this module.',complete:'COMPLETE MODULE',completed:'MODULE COMPLETE ✓',ready:'You collected a pickup, defeated the monster, and gathered its loot.',saved:'Item Spawning progress saved.',saveError:'Could not save module progress. Please try again.',reset:'Demo restarted.',collected:'Pickup collected!',lootCollected:'Loot collected!',lootDropped:n=>`${n} loot items dropped!`,tooFar:'Move closer to attack.',hit:'Hit!',language:'Language'},
  zh:{title:'道具生成 · Godot Forge',back:'← GODOT FORGE / 学习路径',chapter:'第 06 章 / 道具与奖励',language:'语言',eyebrow:'玩法系统 / PHASER 演示',pageTitle:'让探索带来收获。',intro:'拾取物会在随机位置出现，触碰即可收集。击败林地蛮兽后，它会散落战利品。',learningEyebrow:'三个核心概念',learningTitle:'本系统的学习内容',spawnStep:'01 / 随机生成',collectStep:'02 / 接触收集',lootStep:'03 / 敌人掉落',spawnTitle:'随机生成世界道具',spawnCopy:'计时器会在玩家前方生成道具，同时限制场上道具的数量。',collectTitle:'接触式收集',collectCopy:'重叠检测可收集道具、移除其精灵图，并更新玩家计数。',lootTitle:'战斗后的奖励',lootCopy:'击败林地蛮兽后，会随机生成一小堆可收集的战利品。',demoEyebrow:'可游玩的系统演示',demoTitle:'探索、收集、赢取战利品',restart:'重新开始演示',pickups:n=>`已收集 · ${n}`,loot:(collected,total)=>`战利品 · ${collected} / ${total}`,monster:hp=>`林地蛮兽 · ${'♥'.repeat(hp)}`,defeated:'林地蛮兽 · 已击败',objective:'收集一个发光道具，击败怪物，然后收集掉落物。',move:'移动 · A/D 或 ←/→',jump:'跳跃 · W / ↑ / 空格',attack:'挥剑攻击 · 靠近怪物时按 J / X',completion:'完成三个演示任务后即可完成此模块。',complete:'完成模块',completed:'模块已完成 ✓',ready:'你已收集道具、击败怪物并拾取其战利品。',saved:'道具生成进度已保存。',saveError:'无法保存模块进度，请重试。',reset:'演示已重新开始。',collected:'已收集道具！',lootCollected:'已收集战利品！',lootDropped:n=>`掉落了 ${n} 件战利品！`,tooFar:'请靠近后再攻击。',hit:'命中！',language:'语言'},
  ms:{title:'Penjanaan Item · Godot Forge',back:'← GODOT FORGE / LALUAN PEMBELAJARAN',chapter:'BAB 06 / ITEM & GANJARAN',language:'Bahasa',eyebrow:'SISTEM PERMAINAN / DEMO PHASER',pageTitle:'Jadikan penerokaan berbaloi.',intro:'Item muncul pada kedudukan rawak dan boleh dikutip dengan menyentuhnya. Tewaskan raksasa rimba untuk menaburkan loot.',learningEyebrow:'TIGA IDEA UTAMA',learningTitle:'Perkara yang dipelajari',spawnStep:'01 / PERATURAN KEMUNCULAN',collectStep:'02 / PENGUTIPAN',lootStep:'03 / LOOT MUSUH',spawnTitle:'Item dunia rawak',spawnCopy:'Pemasa menghasilkan item di hadapan pemain sambil mengehadkan jumlah item di dunia.',collectTitle:'Kutipan melalui sentuhan',collectCopy:'Pengesanan pertindihan mengutip item, membuang spritenya dan mengemas kini kaunter pemain.',lootTitle:'Ganjaran selepas pertarungan',lootCopy:'Menewaskan raksasa rimba akan menghasilkan sejumlah loot rawak yang boleh dikutip.',demoEyebrow:'DEMO SISTEM BOLEH DIMAINKAN',demoTitle:'Teroka, kutip, dapatkan loot',restart:'MULA SEMULA DEMO',pickups:n=>`ITEM DIKUTIP · ${n}`,loot:(collected,total)=>`LOOT · ${collected} / ${total}`,monster:hp=>`RAKSASA RIMBA · ${'♥'.repeat(hp)}`,defeated:'RAKSASA RIMBA · TEWAS',objective:'Kutip satu item bercahaya, tewaskan raksasa, kemudian kutip lootnya.',move:'GERAK · A/D ATAU ←/→',jump:'LOMPAT · W / ↑ / SPACE',attack:'HAYUN PEDANG · J / X BERHAMPIRAN RAKSASA',completion:'Selesaikan tiga tugasan demo untuk menamatkan modul ini.',complete:'LENGKAPKAN MODUL',completed:'MODUL SELESAI ✓',ready:'Anda mengutip item, menewaskan raksasa dan mengutip lootnya.',saved:'Kemajuan Penjanaan Item disimpan.',saveError:'Kemajuan modul tidak dapat disimpan. Sila cuba lagi.',reset:'Demo dimulakan semula.',collected:'Item telah dikutip!',lootCollected:'Loot telah dikutip!',lootDropped:n=>`${n} item loot dijatuhkan!`,tooFar:'Dekati raksasa untuk menyerang.',hit:'Kena!',language:'Bahasa'},
};
const promptUi={
  en:{eyebrow:'AI ART DIRECTION / REUSABLE PROMPTS',title:'The prompts behind the art',intro:'These prompts describe the generated sprite sheets. Switch language to read each prompt in English, Chinese, or Malay.',pickupTitle:'Forest pickup sprite sheet',monsterTitle:'Grove brute sprite sheet',explorerTitle:'Sword-wielding explorer sprite sheet',badge:'GPT IMAGE 2.5 SUNBURST / ASSET PROMPT',copy:'COPY PROMPT',copied:'Asset prompt copied.',copyError:'Could not copy the prompt.'},
  zh:{eyebrow:'AI 美术设定 / 可复用提示词',title:'美术素材生成提示词',intro:'以下提示词说明了生成的精灵图素材表。切换语言即可阅读每条提示词的英文、中文或马来文版本。',pickupTitle:'森林拾取物精灵图素材表',monsterTitle:'林地蛮兽精灵图素材表',explorerTitle:'持剑探险者精灵图素材表',badge:'GPT IMAGE 2.5 SUNBURST / 素材提示词',copy:'复制提示词',copied:'素材提示词已复制。',copyError:'无法复制提示词。'},
  ms:{eyebrow:'ARAHAN SENI AI / PROM BOLEH GUNA SEMULA',title:'Prom di sebalik seni',intro:'Prom ini menerangkan helaian sprite yang dijana. Tukar bahasa untuk membaca setiap prom dalam bahasa Inggeris, Cina atau Melayu.',pickupTitle:'Helaian sprite item hutan',monsterTitle:'Helaian sprite raksasa rimba',explorerTitle:'Helaian sprite pengembara bersenjata pedang',badge:'GPT IMAGE 2.5 SUNBURST / PROM ASET',copy:'SALIN PROM',copied:'Prom aset telah disalin.',copyError:'Prom tidak dapat disalin.'},
};
const assetPrompts={
  en:{pickup:'Use GPT Image 2.5 Sunburst to create a transparent-background 2D pixel-art pickup sprite sheet for a side-scrolling fantasy forest game. Exact 3 columns × 1 row, one centered collectible per equal cell: (1) radiant teal-and-lime crystal shard, (2) vivid violet woodland mushroom, (3) golden seed pod with two green leaves. Crisp readable pixel clusters, polished hand-crafted game art, consistent scale and generous clear spacing. True transparent alpha; no scenery, text, labels, borders, watermark, duplicates, or cropped objects.',monster:'Use GPT Image 2.5 Sunburst to create a transparent-background side-view pixel-art animation sheet for a forest platform-game enemy: a formidable moss-armored boar-like grove brute with amber eyes and luminous leaf markings. Exact 4 columns × 2 rows with eight equal cells, consistent character scale, baseline, proportions, and center position. Top row: four clear walking-cycle poses facing right. Bottom row: four distinct combat/defeat poses progressing through a wind-up, lunge, hit reaction, and grounded fallen pose. Crisp readable pixel clusters, earthy forest greens, teal shadows, warm amber accents. Keep the full character inside each cell with transparent padding; no scenery, grid lines, text, labels, watermark, cropped parts, or duplicates.',explorer:'Use GPT Image 2.5 Sunburst to create a transparent-background 2D pixel-art side-scroller player sprite sheet: one brave forest explorer with short brown hair, a teal-green tunic, purple scarf, leather boots, and a clearly visible steel sword held in the right hand. Exact 8 columns × 7 rows, 56 equal 256×256 cells, one complete centered character per cell, consistent scale, baseline, proportions and orientation facing right. Rows in order: idle (one standing pose repeated across all eight cells), walk (eight distinct alternating footfall poses with crossed legs), run (eight faster poses), sword attack (four clear readable sword-swing poses; sword must be visible and part of the character in every attack frame), jump (four poses), hurt (four poses), death (four poses). Keep the complete body and sword inside each cell with generous transparent padding. Crisp readable pixel clusters, polished hand-crafted game art, consistent forest-adventure palette. True transparent alpha; no background, scenery, grid lines, text, labels, watermark, cropped objects, or extra characters.'},
  zh:{pickup:'使用 GPT Image 2.5 Sunburst，为横向卷轴奇幻森林游戏制作一张透明背景的 2D 像素风拾取物精灵图素材表。严格采用 3 列 × 1 行，每个等宽格子居中放置一个不同的收藏道具：(1) 青绿色与亮绿色的发光水晶碎片；(2) 鲜艳紫色的森林蘑菇；(3) 带两片绿叶的金色种荚。像素块清晰易读，具有精致手绘游戏美术质感，三个道具尺寸一致并留有足够间距。使用真正的透明 Alpha；不要背景场景、文字、标签、边框、水印、重复道具或被裁切的物体。',monster:'使用 GPT Image 2.5 Sunburst，为森林平台游戏敌人制作一张透明背景、侧视角的像素风动画素材表：一只强悍的苔藓护甲野猪形林地蛮兽，拥有琥珀色眼睛和发光叶片纹饰。严格采用 4 列 × 2 行，共八个等大的格子；每格角色的比例、基线和中心位置保持一致。第一行：面朝右方的四个清晰行走循环姿势。第二行：四个明显不同的战斗／倒地姿势，依次表现蓄力、冲刺、受击反应和倒地。像素块清晰，使用森林绿、蓝绿色阴影和暖琥珀色点缀。角色完整置于各自格子并留有透明边距；不要场景、网格线、文字、标签、水印、重复角色或裁切部分。',explorer:'使用 GPT Image 2.5 Sunburst，为横向卷轴平台游戏制作透明背景的 2D 像素风玩家角色精灵图素材表：一名勇敢的森林探险者，棕色短发、蓝绿色 tunic、紫色围巾、皮靴，右手清晰握着钢剑。严格采用 8 列 × 7 行，共 56 个 256×256 等大格子；每格只放置一个完整居中的角色，比例、基线、尺寸和朝向保持一致，角色面朝右方。各行依次为：待机（8 格重复同一个站立姿势）、行走（8 个双腿交替且有交叉步态的姿势）、奔跑（8 个更快速的姿势）、挥剑攻击（4 个清楚易辨的挥剑姿势；每一帧中剑都必须清晰可见并属于角色的一部分）、跳跃（4 个姿势）、受伤（4 个姿势）、死亡（4 个姿势）。每格完整呈现身体与剑，并留出充足透明边距。像素块清晰，手绘游戏美术质感精致，采用一致的森林冒险配色。使用真正透明 Alpha；不要背景、场景、网格线、文字、标签、水印、裁切物体或额外角色。'},
  ms:{pickup:'Gunakan GPT Image 2.5 Sunburst untuk menghasilkan helaian sprite item kutipan seni piksel 2D berlatar lutsinar bagi permainan hutan fantasi sisi tatal. Susun tepat dalam 3 lajur × 1 baris; satu item berbeza di tengah setiap sel sama lebar: (1) serpihan kristal bercahaya warna teal dan hijau limau, (2) cendawan hutan ungu terang, (3) pod biji emas dengan dua helai daun hijau. Kelompok piksel yang jelas dan mudah dibaca, seni permainan buatan tangan yang kemas, saiz seragam dan jarak yang mencukupi. Gunakan alpha lutsinar sebenar; tanpa latar pemandangan, teks, label, garisan sempadan, tera air, item pendua atau objek terpotong.',monster:'Gunakan GPT Image 2.5 Sunburst untuk menghasilkan helaian animasi seni piksel pandangan sisi berlatar lutsinar bagi musuh permainan platform hutan: raksasa rimba seperti babi hutan yang gagah dengan perisai lumut, mata ambar dan corak daun bercahaya. Susun tepat dalam 4 lajur × 2 baris dengan lapan sel sama besar; skala, garis dasar, perkadaran dan kedudukan watak kekal konsisten. Baris atas: empat pose kitaran berjalan yang jelas menghadap ke kanan. Baris bawah: empat pose berlawan/tewas yang berbeza, mengikut urutan bersedia menyerang, menerjang, terkena serangan dan terbaring di tanah. Kelompok piksel yang jelas, warna hijau hutan, bayang teal dan aksen ambar hangat. Watak penuh dengan ruang lutsinar dalam setiap sel; tanpa pemandangan, garisan grid, teks, label, tera air, bahagian terpotong atau pendua.',explorer:'Gunakan GPT Image 2.5 Sunburst untuk menghasilkan helaian sprite watak pemain seni piksel 2D berlatar lutsinar untuk permainan platform sisi tatal: seorang pengembara hutan yang berani, berambut perang pendek, memakai tunik teal-hijau, skarf ungu dan but kulit, dengan pedang keluli yang jelas di tangan kanan. Susun tepat dalam 8 lajur × 7 baris, 56 sel sama besar berukuran 256×256; satu watak lengkap di tengah setiap sel dengan skala, garis dasar, perkadaran dan orientasi menghadap ke kanan yang konsisten. Susunan baris: pegun (pose berdiri yang sama diulang dalam lapan sel), berjalan (lapan pose langkah berselang-seli dengan kaki bersilang), berlari (lapan pose lebih pantas), serangan pedang (empat pose hayunan pedang yang jelas; pedang mesti kelihatan dan menjadi sebahagian watak dalam setiap bingkai serangan), lompat (empat pose), cedera (empat pose), mati (empat pose). Pastikan seluruh badan dan pedang muat dalam setiap sel dengan ruang lutsinar yang luas. Kelompok piksel yang jelas dan seni permainan buatan tangan yang kemas dengan palet pengembaraan hutan yang konsisten. Alpha lutsinar sebenar; tanpa latar, pemandangan, garisan grid, teks, label, tera air, objek terpotong atau watak tambahan.'},
};
let locale=copy[localStorage.getItem('godot-forge-locale')]?localStorage.getItem('godot-forge-locale'):'en';
const bindings={'back-link':'back','chapter-label':'chapter','intro-eyebrow':'eyebrow','page-title':'pageTitle','intro-copy':'intro','learning-eyebrow':'learningEyebrow','learning-title':'learningTitle','spawn-step':'spawnStep','collect-step':'collectStep','loot-step':'lootStep','spawn-title':'spawnTitle','spawn-copy':'spawnCopy','collect-title':'collectTitle','collect-copy':'collectCopy','loot-title':'lootTitle','loot-copy':'lootCopy','demo-eyebrow':'demoEyebrow','demo-title':'demoTitle','restart-demo':'restart','move-help':'move','jump-help':'jump','attack-help':'attack','completion-status':'completion','complete-module':'complete'};
const t=()=>copy[locale];
let game,scene,player,monster,pickupGroup,overlap,cursors,keys,spawnTimer,attackAt=0,playerAttackUntil=0,playerFacing=1,monsterHp=2,monsterDead=false,monsterDefeatedOnce=false,monsterDeathSequenceStarted=false,pickupsCollected=0,lootCollected=0,lootDropped=0,completed=false,completionReady=false;
const WORLD_WIDTH=1920,WIDTH=960,HEIGHT=576,FLOOR_Y=516,MONSTER_GROUND_Y=FLOOR_Y+18;

function applyCopy(){document.title=t().title;document.documentElement.lang=locale==='zh'?'zh-CN':locale;document.querySelectorAll('[data-locale]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.locale===locale)));for(const [id,key] of Object.entries(bindings)){const el=$(`#${id}`);if(el)el.textContent=t()[key];}const labels=promptUi[locale];$('#prompts-eyebrow').textContent=labels.eyebrow;$('#prompts-title').textContent=labels.title;$('#prompts-intro').textContent=labels.intro;$('#pickup-prompt-title').textContent=labels.pickupTitle;$('#monster-prompt-title').textContent=labels.monsterTitle;$('#explorer-prompt-title').textContent=labels.explorerTitle;document.querySelectorAll('.prompt-badge').forEach(el=>el.textContent=labels.badge);document.querySelectorAll('[data-copy-prompt]').forEach(button=>button.textContent=labels.copy);$('#pickup-prompt').textContent=assetPrompts[locale].pickup;$('#monster-prompt').textContent=assetPrompts[locale].monster;$('#explorer-prompt').textContent=assetPrompts[locale].explorer;scene?.children.list.filter(child=>child.getData?.('monster-label')).forEach(child=>child.setText(monsterDead?t().defeated:t().monster(monsterHp)));updateHud();}
function updateHud(){if(!$('#pickup-counter'))return;$('#pickup-counter').textContent=t().pickups(pickupsCollected);$('#loot-counter').textContent=t().loot(lootCollected,lootDropped);$('#monster-counter').textContent=monsterDead?t().defeated:t().monster(monsterHp);$('#objective-hint').textContent=t().objective;$('#complete-module').disabled=!completionReady||completed;if(completed)$('#complete-module').textContent=t().completed;}
function updateCompletion(){completionReady=pickupsCollected>0&&monsterDefeatedOnce&&lootCollected>0;if(completionReady)$('#completion-status').textContent=t().ready;updateHud();}
function texturePreload(){this.load.setCORS('anonymous');this.load.image('forest-far','https://godot-forge.sgp1.digitaloceanspaces.com/2d-game-development/parallax-tiling-map/images/parallax-far.webp');this.load.image('forest-mid','https://godot-forge.sgp1.digitaloceanspaces.com/2d-game-development/parallax-tiling-map/images/parallax-midground.webp');this.load.spritesheet('explorer','https://godot-forge.sgp1.digitaloceanspaces.com/2d-game-development/items-spawning/images/forest-sword-explorer.png',{frameWidth:256,frameHeight:256});this.load.spritesheet('forest-pickups','https://godot-forge.sgp1.digitaloceanspaces.com/2d-game-development/items-spawning/images/forest-pickups.png',{frameWidth:724,frameHeight:724});this.load.spritesheet('grove-brute','https://godot-forge.sgp1.digitaloceanspaces.com/2d-game-development/items-spawning/images/grove-brute-sprites.png',{frameWidth:443,frameHeight:443});}
function makeGround(){const g=this.add.graphics();g.fillStyle(0x263f2d).fillRect(0,FLOOR_Y,WORLD_WIDTH,HEIGHT-FLOOR_Y);g.fillStyle(0x78a84a).fillRect(0,FLOOR_Y,WORLD_WIDTH,9);g.fillStyle(0x3b5c35);for(let x=0;x<WORLD_WIDTH;x+=64)g.fillRoundedRect(x+6,FLOOR_Y+22,38,8,3);}
function makeAnims(){const anims=this.anims;anims.create({key:'hero-idle',frames:anims.generateFrameNumbers('explorer',{start:0,end:0}),frameRate:5,repeat:-1});anims.create({key:'hero-walk',frames:anims.generateFrameNumbers('explorer',{start:8,end:15}),frameRate:9,repeat:-1});anims.create({key:'hero-run',frames:anims.generateFrameNumbers('explorer',{start:16,end:23}),frameRate:13,repeat:-1});anims.create({key:'hero-attack',frames:anims.generateFrameNumbers('explorer',{start:24,end:27}),frameRate:12,repeat:0});anims.create({key:'hero-jump',frames:anims.generateFrameNumbers('explorer',{start:32,end:35}),frameRate:12,repeat:0});anims.create({key:'hero-hurt',frames:anims.generateFrameNumbers('explorer',{start:40,end:43}),frameRate:12,repeat:0});anims.create({key:'hero-death',frames:anims.generateFrameNumbers('explorer',{start:48,end:51}),frameRate:10,repeat:0});anims.create({key:'brute-walk',frames:anims.generateFrameNumbers('grove-brute',{start:0,end:3}),frameRate:7,repeat:-1});anims.create({key:'brute-fall',frames:anims.generateFrameNumbers('grove-brute',{start:5,end:7}),frameRate:5,repeat:0});}
function create(){scene=this;this.physics.world.setBounds(0,0,WORLD_WIDTH,HEIGHT);this.cameras.main.setBounds(0,0,WORLD_WIDTH,HEIGHT).setBackgroundColor('#17332a');
  this.add.tileSprite(0,0,WORLD_WIDTH,HEIGHT,'forest-far').setOrigin(0).setScrollFactor(.12).setDepth(-10).setTint(0xd5e6db);
  this.add.tileSprite(0,95,WORLD_WIDTH,HEIGHT-95,'forest-mid').setOrigin(0).setScrollFactor(.32).setDepth(-5).setAlpha(.6);
  makeGround.call(this);makeAnims.call(this);
  const floor=this.add.rectangle(WORLD_WIDTH/2,FLOOR_Y+48,WORLD_WIDTH,96,0x000000,0);this.physics.add.existing(floor,true);floor.setVisible(false);
  player=this.physics.add.sprite(100,FLOOR_Y,'explorer',0).setScale(.34).setOrigin(.5,.94).setDepth(8).setCollideWorldBounds(true);player.body.setSize(140,200).setOffset(58,35);this.physics.add.collider(player,floor);
  monster=this.physics.add.sprite(1390,MONSTER_GROUND_Y,'grove-brute',0).setDisplaySize(132,132).setOrigin(.5,1).setDepth(7).setImmovable(true).setCollideWorldBounds(true);monster.body.setAllowGravity(false);monster.setVelocityX(-35);monster.play('brute-walk');
  pickupGroup=this.physics.add.group({allowGravity:false,immovable:true});overlap=this.physics.add.overlap(player,pickupGroup,collectPickup,null,this);
  this.add.text(monster.x,FLOOR_Y-133,t().monster(monsterHp),{fontFamily:'ui-monospace,monospace',fontSize:'11px',fontStyle:'bold',color:'#edf5e9',backgroundColor:'#102019dd',padding:{x:6,y:4}}).setOrigin(.5).setDepth(12).setData('monster-label',true);
  let firstPickupX=Phaser.Math.Between(145,195);for(let i=0;i<5;i++){if(i>0)firstPickupX+=Phaser.Math.Between(150,265);createPickup(firstPickupX,FLOOR_Y-28,false);}
  spawnTimer=this.time.addEvent({delay:3200,loop:true,callback:()=>{if(pickupGroup.countActive(true)<10){const x=randomSpawnX();if(x!==null)createPickup(x,FLOOR_Y-28,false);}}});
  cursors=this.input.keyboard.createCursorKeys();keys=this.input.keyboard.addKeys('A,D,W,J,X');
  this.cameras.main.startFollow(player,true,.1,.08);this.cameras.main.setDeadzone(260,100);
}
function findSpacedPickupX(min,max,minGap){if(max<=min)return null;const activeX=pickupGroup?.getChildren().filter(item=>item.active).map(item=>item.x)||[];for(let attempt=0;attempt<28;attempt++){const candidate=Phaser.Math.Between(Math.ceil(min),Math.floor(max));if(activeX.every(x=>Math.abs(x-candidate)>=minGap))return candidate;}return null;}
function randomSpawnX(){const nearMin=Math.max(120,player.x+240),nearMax=Math.min(WORLD_WIDTH-80,player.x+780);return findSpacedPickupX(nearMin,nearMax,160)??findSpacedPickupX(80,WORLD_WIDTH-70,160);}
function createPickup(x,y,isLoot){if(!pickupGroup||!scene)return;const item=pickupGroup.create(x,y,'forest-pickups',Phaser.Math.Between(0,2)).setDisplaySize(42,42).setDepth(9);item.body.setAllowGravity(false).setImmovable(true);item.setData('loot',isLoot);if(!matchMedia('(prefers-reduced-motion: reduce)').matches)scene.tweens.add({targets:item,y:y-9,duration:620,yoyo:true,repeat:-1,ease:'Sine.easeInOut'});return item;}
function collectPickup(_hero,item){if(!item.active)return;const loot=item.getData('loot');if(loot)lootCollected++;else pickupsCollected++;scene.tweens.killTweensOf(item);item.destroy();window.showToast?.(loot?t().lootCollected:t().collected,'success');updateCompletion();}
function respawnMonster(){if(!monster?.active)return;const respawnX=Phaser.Math.Distance.Between(monster.x,player.x)<260?1390:monster.x;monsterHp=2;monster.setPosition(respawnX,MONSTER_GROUND_Y).setAlpha(0).setVisible(true).clearTint();monster.body.reset(respawnX,MONSTER_GROUND_Y);monster.body.enable=false;monster.play('brute-walk');const label=scene.children.list.find(child=>child.getData?.('monster-label'));if(label){label.setPosition(respawnX,FLOOR_Y-133).setText(t().defeated);}scene.tweens.add({targets:monster,alpha:1,duration:550,ease:'Sine.easeOut',onComplete:()=>{if(!monster?.active)return;monsterDead=false;monsterDeathSequenceStarted=false;monster.body.enable=true;monster.setVelocityX(-35);if(label)label.setText(t().monster(monsterHp));updateHud();}});}
function finishMonsterDeath(){if(!monster?.active||monsterDeathSequenceStarted)return;monsterDeathSequenceStarted=true;scene.time.delayedCall(850,()=>{if(!monster?.active)return;scene.tweens.add({targets:monster,alpha:0,duration:400,ease:'Sine.easeIn',onComplete:()=>scene.time.delayedCall(1100,respawnMonster)});});}
function attackMonster(){const now=scene.time.now;if(now-attackAt<420)return;attackAt=now;playerAttackUntil=now+360;player.anims.play('hero-attack',true);const direction=playerFacing;if(monsterDead||Math.abs(monster.x-player.x)>105||Math.abs(monster.y-player.y)>100||((monster.x-player.x)*direction)<-12){window.showToast?.(t().tooFar);return;}monsterHp--;monster.setTint(0xffbd78);scene.time.delayedCall(130,()=>monster?.clearTint());if(monsterHp<=0){monsterDead=true;monsterDefeatedOnce=true;monsterDeathSequenceStarted=false;monster.setVelocityX(0);monster.play('brute-fall');monster.once('animationcomplete-brute-fall',finishMonsterDeath);scene.time.delayedCall(900,finishMonsterDeath);const count=Phaser.Math.Between(3,5);for(let i=0;i<count;i++){const x=findSpacedPickupX(Math.max(45,monster.x-235),Math.min(WORLD_WIDTH-45,monster.x+235),68);if(x!==null&&createPickup(x,FLOOR_Y-30,true))lootDropped++;}scene.children.list.filter(child=>child.getData?.('monster-label')).forEach(child=>child.setText(t().defeated));}else window.showToast?.(t().hit,'success');updateCompletion();}
function update(){if(!player)return;const left=cursors.left.isDown||keys.A.isDown,right=cursors.right.isDown||keys.D.isDown,jump=Phaser.Input.Keyboard.JustDown(cursors.up)||Phaser.Input.Keyboard.JustDown(cursors.space)||Phaser.Input.Keyboard.JustDown(keys.W),grounded=player.body.blocked.down||player.body.touching.down;player.setVelocityX(left?-220:right?220:0);if(left)playerFacing=-1;else if(right)playerFacing=1;if(jump&&grounded)player.setVelocityY(-470);if(Phaser.Input.Keyboard.JustDown(keys.J)||Phaser.Input.Keyboard.JustDown(keys.X))attackMonster();if(!monsterDead){if(monster.x<1240)monster.setVelocityX(38);if(monster.x>1540)monster.setVelocityX(-38);monster.setFlipX(monster.body.velocity.x<0);const label=scene.children.list.find(child=>child.getData?.('monster-label'));if(label)label.x=monster.x;}player.setFlipX(playerFacing<0);if(scene.time.now<playerAttackUntil)player.anims.play('hero-attack',true);else if(!grounded)player.anims.play('hero-jump',true);else if(left||right)player.anims.play(Math.abs(player.body.velocity.x)>260?'hero-run':'hero-walk',true);else player.anims.play('hero-idle',true);}
function initGame({preserveCompletion=false}={}){const wasCompleted=completed;if(game){game.destroy(true);game=null;}pickupGroup=null;player=null;monster=null;monsterDead=false;monsterDefeatedOnce=false;monsterDeathSequenceStarted=false;monsterHp=2;pickupsCollected=0;lootCollected=0;lootDropped=0;completionReady=false;attackAt=0;playerAttackUntil=0;playerFacing=1;completed=preserveCompletion&&wasCompleted;$('#complete-module').textContent=completed?t().completed:t().complete;$('#completion-status').textContent=t().completion;game=new Phaser.Game({type:Phaser.AUTO,parent:'items-stage',width:WIDTH,height:HEIGHT,backgroundColor:'#17332a',physics:{default:'arcade',arcade:{gravity:{y:1100},debug:false}},scene:{preload:texturePreload,create,update},scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH}});updateHud();}
async function markCompleted(){if(!completionReady||completed)return;const button=$('#complete-module');button.disabled=true;try{const response=await fetch(`/api/modules/${slug}/progress`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({learnerId,completed:true})});if(!response.ok)throw new Error();completed=true;$('#completion-status').textContent=t().saved;window.showToast?.(t().saved,'success');}catch{$('#completion-status').textContent=t().saveError;window.showToast?.(t().saveError,'error');}finally{updateHud();}}
$('#languages').addEventListener('click',event=>{const next=event.target.closest('[data-locale]')?.dataset.locale;if(!copy[next])return;locale=next;localStorage.setItem('godot-forge-locale',locale);applyCopy();});
$('#restart-demo').addEventListener('click',()=>{initGame({preserveCompletion:true});window.showToast?.(t().reset,'success');});
$('#complete-module').addEventListener('click',markCompleted);
document.querySelectorAll('[data-copy-prompt]').forEach(button=>button.addEventListener('click',async()=>{const prompt=assetPrompts[locale][button.dataset.copyPrompt];try{await navigator.clipboard.writeText(prompt);window.showToast?.(promptUi[locale].copied,'success');}catch{window.showToast?.(promptUi[locale].copyError,'error');}}));
window.addEventListener('godot-forge-module-reset',event=>{if(event.detail?.slug===slug){completed=false;initGame();}});
applyCopy();
initGame();
fetch(`/api/modules?learnerId=${encodeURIComponent(learnerId)}`).then(response=>response.json()).then(modules=>{completed=Boolean(modules.find(module=>module.slug===slug)?.completed);updateHud();}).catch(()=>{});
