import assert from 'node:assert/strict';
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import { chromium } from 'playwright-core';

const storage = await mkdtemp(join(tmpdir(), 'godot-forge-leaderboard-test-'));
const server = spawn(process.execPath, ['server.js'], { cwd: new URL('..', import.meta.url), env: { ...process.env, PORT: '0', APP_STORAGE_DIR: storage, OPENAI_API_KEY: '' }, stdio: ['ignore', 'pipe', 'pipe'] });
let output = '';
let browser;
try {
  const baseUrl = await new Promise((resolve, reject) => {
    const timeout = setTimeout(() => reject(new Error(`Leaderboard test server timed out: ${output}`)), 10000);
    server.once('error', error => { clearTimeout(timeout); reject(error); });
    server.once('exit', code => { clearTimeout(timeout); reject(new Error(`Leaderboard test server exited ${code}: ${output}`)); });
    server.stdout.on('data', chunk => { output += chunk; const match = output.match(/http:\/\/localhost:(\d+)/); if (match) { clearTimeout(timeout); resolve(`http://127.0.0.1:${match[1]}`); } });
  });
  browser = await chromium.launch({ channel: process.env.CHROME_CHANNEL || 'chrome', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.addInitScript(() => {
    const original = CanvasRenderingContext2D.prototype.drawImage;
    window.walkFrames = new Set();
    CanvasRenderingContext2D.prototype.drawImage = function (image, ...args) {
      if (image instanceof HTMLImageElement && image.src.includes('forest-sword-explorer.png') && args.length === 8 && args[1] === 256) window.walkFrames.add(args[0]);
      return original.call(this, image, ...args);
    };
  });
  await page.goto(`${baseUrl}/game-leaderboard/`);
  await page.locator('#leaderboard-stage').waitFor();
  for (const name of ['dusk-arena', 'leaderboard-crest']) assert.equal((await page.request.get(`${baseUrl}/game-leaderboard/images/${name}.webp`)).status(), 200);
  assert.equal(await page.locator('.prompt-card').count(), 2);
  await page.locator('.prompt-card summary').first().click();
  assert.match(await page.locator('.prompt-card pre').first().textContent(), /enchanted woodland sprint course/);
  assert.equal(await page.locator('a[href$=".txt"]').count(), 0);
  assert.equal(await page.locator('#gold-count').textContent(), '0 / 10');
  assert.equal(await page.locator('#heart-count').textContent(), '0 / 1');
  assert.equal(await page.locator('#score-count').textContent(), '0');
  assert.equal(await page.locator('#complete-module').isDisabled(), true);
  await page.click('#tab-board');
  assert.equal(await page.locator('#leaderboard-card.is-locked').count(), 1);
  assert.match(await page.locator('#board-crest').evaluate(node => getComputedStyle(node).filter), /grayscale/);
  assert.equal(await page.locator('.rank-row.is-you').count(), 0);
  await page.click('#tab-play');
  await page.locator('#leaderboard-stage').click();
  await page.keyboard.down('ArrowRight');
  await page.waitForFunction(() => document.querySelector('#heart-count')?.textContent === '1 / 1');
  await page.keyboard.up('ArrowRight');
  assert.ok(await page.evaluate(() => window.walkFrames.size >= 4), 'the explorer should display multiple walking frames');
  assert.equal(await page.locator('#gold-count').textContent(), '5 / 10');
  assert.equal(await page.locator('#score-count').textContent(), '100');
  await page.click('#view-board');
  assert.equal(await page.locator('#leaderboard-card.is-locked').count(), 1);
  await page.click('#back-to-play');
  await page.locator('#leaderboard-stage').click();
  await page.keyboard.down('ArrowRight');
  await page.waitForFunction(() => document.querySelector('#score-count')?.textContent === '150');
  await page.keyboard.up('ArrowRight');
  await page.locator('#board-panel').waitFor({ state: 'visible' });
  assert.equal(await page.locator('#leaderboard-card.is-earned.is-revealing').count(), 1);
  assert.equal(await page.locator('.rank-row.is-you').count(), 1);
  await page.waitForFunction(() => document.querySelector('#you-score')?.textContent === '150');
  assert.equal(await page.locator('#board-crest').evaluate(node => getComputedStyle(node).filter), 'none');
  assert.equal(await page.locator('#board-total').textContent(), '150 PTS');
  assert.deepEqual(await page.locator('.rank-row > span:first-child').allTextContents(), ['#1', '#2', '#3', '#4']);
  const learnerId = await page.evaluate(() => localStorage.getItem('godot-forge-learner-id'));
  await page.waitForFunction(async id => {
    const response = await fetch(`/api/modules/game-leaderboard/checkpoint?learnerId=${encodeURIComponent(id)}`);
    const state = (await response.json()).state;
    return state?.collected?.length === 10 && state.heartCollected === true;
  }, learnerId);
  await page.reload();
  await page.click('#tab-board');
  assert.equal(await page.locator('#leaderboard-card.is-earned').count(), 1);
  assert.equal(await page.locator('.rank-row.is-you').count(), 1);
  assert.equal(await page.locator('#board-total').textContent(), '150 PTS');
  await page.click('#tab-play');
  assert.equal(await page.locator('#score-count').textContent(), '150');
  assert.equal(await page.locator('#complete-module').isEnabled(), true);
  await page.click('#complete-module');
  await page.waitForFunction(async id => (await (await fetch(`/api/modules?learnerId=${encodeURIComponent(id)}`)).json()).find(module => module.slug === 'game-leaderboard')?.completed === true, learnerId);
  await page.click('[data-locale="zh"]');
  assert.equal(await page.locator('html').getAttribute('lang'), 'zh-CN');
  assert.match(await page.locator('#page-title').textContent(), /排行榜/);
  await page.click('[data-locale="ms"]');
  assert.equal(await page.locator('html').getAttribute('lang'), 'ms');
  assert.match(await page.locator('#page-title').textContent(), /puncak/i);
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.click('#tab-board');
  await page.click('#reset-module');
  assert.equal(await page.locator('#reset-module').getAttribute('data-confirming'), 'true');
  const resetResponse = page.waitForResponse(response => response.url().endsWith('/api/modules/game-leaderboard/reset') && response.ok());
  const resetNavigation = page.waitForNavigation({ waitUntil: 'load' });
  await page.click('#reset-module');
  await Promise.all([resetResponse, resetNavigation]);
  await page.waitForFunction(() => document.querySelector('#score-count')?.textContent === '0');
  assert.equal(await page.locator('#gold-count').textContent(), '0 / 10');
  assert.equal(await page.locator('#heart-count').textContent(), '0 / 1');
  assert.equal(await page.locator('#world-progress').textContent(), '0%');
  await page.click('#tab-board');
  assert.equal(await page.locator('#leaderboard-card.is-locked').count(), 1);
  assert.equal(await page.locator('.rank-row.is-you').count(), 0);
  assert.equal((await (await page.request.get(`${baseUrl}/api/modules/game-leaderboard/checkpoint?learnerId=${learnerId}`)).json()).state, null);
  assert.equal((await (await page.request.get(`${baseUrl}/api/modules?learnerId=${learnerId}`)).json()).find(module => module.slug === 'game-leaderboard').completed, false);
  await page.reload();
  assert.equal(await page.locator('#score-count').textContent(), '0');
  await page.click('#tab-board');
  assert.equal(await page.locator('#leaderboard-card.is-locked').count(), 1);
  assert.deepEqual(errors, []);
  console.log('PASS scoring, animated leaderboard, grey-to-color state, walking frames, saved progress, localization, mobile layout, and reset');
} finally {
  if (browser) await browser.close();
  if (server.exitCode === null) { const exited = once(server, 'exit'); server.kill('SIGTERM'); await exited; }
}
