import assert from 'node:assert/strict';
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import { chromium } from 'playwright-core';
import sharp from 'sharp';

const storage = await mkdtemp(join(tmpdir(), 'godot-forge-parallax-test-'));
const child = spawn(process.execPath, ['server.js'], { cwd:new URL('..',import.meta.url), env:{...process.env,PORT:'0',APP_STORAGE_DIR:storage,OPENAI_API_KEY:''}, stdio:['ignore','pipe','pipe'] });
let output='',errors=''; child.stderr.on('data',chunk=>{errors+=chunk;});
const baseUrl = await new Promise((resolve,reject)=>{
  const timer=setTimeout(()=>reject(new Error(`Parallax test server timeout: ${errors}`)),10000);
  child.on('exit',code=>{clearTimeout(timer);reject(new Error(`Server exited ${code}: ${errors}`));});
  child.stdout.on('data',chunk=>{output+=chunk;const match=output.match(/http:\/\/localhost:(\d+)/);if(match){clearTimeout(timer);resolve(`http://127.0.0.1:${match[1]}`);}});
});
let browser;
try {
  const tilePng=await sharp(Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="256" height="256"><rect width="256" height="256" fill="#29483a"/><path d="M0 64h256M0 128h256M0 192h256M64 0v256M128 0v256M192 0v256" stroke="#c4f265" stroke-width="4"/></svg>')).png().toBuffer();
  const tileImage=await (await fetch(`${baseUrl}/api/assets?module=final-game`,{method:'POST',headers:{'content-type':'image/png','x-file-name':'test-tiles.png'},body:tilePng})).json();
  const tileManifest={version:1,kind:'asset-pack',category:'tileset',image:{file:'test-tiles.png',assetUrl:tileImage.assetUrl,width:256,height:256},grid:{columns:4,rows:4,cellWidth:64,cellHeight:64},cells:Array.from({length:16},(_,index)=>({index,column:index%4,row:Math.floor(index/4),x:index%4*64,y:Math.floor(index/4)*64,width:64,height:64}))};
  await fetch(`${baseUrl}/api/assets?module=final-game`,{method:'POST',headers:{'content-type':'application/json','x-file-name':'test-tiles.json'},body:JSON.stringify(tileManifest)});
  const characterPng=await sharp(Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="128" height="64"><rect x="16" y="5" width="30" height="55" rx="8" fill="#9c8cff"/><rect x="80" y="5" width="30" height="55" rx="8" fill="#c4f265"/></svg>')).png().toBuffer();
  const characterImage=await (await fetch(`${baseUrl}/api/assets?module=final-game`,{method:'POST',headers:{'content-type':'image/png','x-file-name':'test-character.png'},body:characterPng})).json();
  const characterManifest={version:1,kind:'character',image:{file:'test-character.png',assetUrl:characterImage.assetUrl,width:128,height:64},frameSize:{width:64,height:64},animations:[{name:'idle',fps:2,loop:true,frames:[{x:0,y:0,width:64,height:64}]},{name:'walk',fps:5,loop:true,frames:[{x:0,y:0,width:64,height:64},{x:64,y:0,width:64,height:64}]}]};
  await fetch(`${baseUrl}/api/assets?module=final-game`,{method:'POST',headers:{'content-type':'application/json','x-file-name':'test-character.json'},body:JSON.stringify(characterManifest)});

  browser=await chromium.launch({channel:process.env.CHROME_CHANNEL||'chrome',headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1100}}), pageErrors=[], dialogs=[];
  page.on('pageerror',error=>pageErrors.push(error.message)); page.on('dialog',dialog=>{dialogs.push(dialog.message());dialog.dismiss();});
  await page.goto(`${baseUrl}/parallax-tiling-map/`);
  await page.waitForFunction(()=>window.tilemapWorkshop?.ready);
  assert.equal(await page.evaluate(()=>window.tilemapWorkshop.pageCount),3);
  await page.waitForFunction(()=>document.querySelectorAll('#prompt-grid .prompt-card').length===6);
  assert.equal(await page.locator('#prompt-grid .prompt-card > .prompt-card-body > pre').count(),6);
  assert.match(await page.locator('#prompt-grid pre').first().textContent(),/far parallax background/);
  await page.locator('#prompt-grid [data-prompt-index="0"]').click();
  await page.waitForFunction(()=>[...document.querySelectorAll('.action-toast')].some(item=>item.textContent.includes('prompt copied')));
  assert.equal(await page.locator('#phaser-stage canvas').count(),1);
  assert.equal(await page.locator('#asset-pack option').count(),2);
  assert.equal(await page.locator('#character option').count(),2);
  assert.equal(await page.locator('#tile-palette .tile-option').nth(0).getAttribute('data-animation'),'static');
  assert.equal(await page.locator('#tile-palette .tile-option').nth(9).getAttribute('data-animation'),'glow');
  assert.ok(await page.evaluate(()=>window.tilemapWorkshop.animatedTileCount)>0);
  const initialGlowAlpha=await page.evaluate(()=>window.tilemapWorkshop.animatedGlowAlpha);
  await page.waitForFunction(previous=>Math.abs(window.tilemapWorkshop.animatedGlowAlpha-previous)>.02,initialGlowAlpha);
  assert.match(await page.locator('#tile-palette .tile-option').nth(9).evaluate(element=>getComputedStyle(element.querySelector('.tile-thumb')).animationName),/tile-glow/);
  await page.locator('#tile-palette .tile-option').nth(9).hover();
  assert.equal(await page.locator('#tile-tooltip').isVisible(),true);
  assert.match(await page.locator('#tile-tooltip').textContent(),/Glowing crystal/);
  await page.locator('#tile-palette .tile-option').nth(9).click();
  assert.match(await page.locator('#tile-info-title').textContent(),/Glowing crystal/);
  assert.match(await page.locator('#tile-info-motion').textContent(),/ANIMATED TILE/);
  assert.equal(await page.locator('#play-help').isHidden(),true);
  await page.click('#play-mode');
  assert.equal(await page.locator('#run-help').isVisible(),true);
  await page.waitForFunction(()=>window.tilemapWorkshop.grounded&&window.tilemapWorkshop.movementPhase==='idle');
  const jumpStartY=await page.evaluate(()=>window.tilemapWorkshop.playerY);
  await page.keyboard.down('Space');
  await page.waitForFunction(()=>window.tilemapWorkshop.movementPhase==='rise'&&window.tilemapWorkshop.frameIndex>=13);
  await page.waitForFunction(start=>window.tilemapWorkshop.playerY<start-25,jumpStartY);
  await page.waitForFunction(()=>window.tilemapWorkshop.movementPhase==='apex'&&window.tilemapWorkshop.frameIndex===15);
  await page.waitForFunction(()=>window.tilemapWorkshop.movementPhase==='fall'&&window.tilemapWorkshop.frameIndex>=16);
  await page.waitForFunction(()=>window.tilemapWorkshop.movementPhase==='land'&&window.tilemapWorkshop.frameIndex>=18);
  await page.keyboard.up('Space');
  await page.waitForFunction(()=>window.tilemapWorkshop.grounded&&window.tilemapWorkshop.movementPhase==='idle');
  await page.click('#reset-player');
  await page.waitForFunction(()=>window.tilemapWorkshop.grounded&&window.tilemapWorkshop.jumpsUsed===0);
  await page.keyboard.down('Space');
  await page.waitForFunction(()=>!window.tilemapWorkshop.grounded&&window.tilemapWorkshop.jumpsUsed===1);
  await page.keyboard.up('Space');
  await page.waitForFunction(()=>!window.tilemapWorkshop.grounded&&window.tilemapWorkshop.movementPhase==='fall');
  const secondJumpY=await page.evaluate(()=>window.tilemapWorkshop.playerY);
  await page.keyboard.down('Space');
  await page.waitForFunction(()=>window.tilemapWorkshop.jumpsUsed===2&&window.tilemapWorkshop.velocityY<-300);
  await page.waitForFunction(start=>window.tilemapWorkshop.playerY<start-20,secondJumpY);
  await page.keyboard.up('Space');
  await page.waitForFunction(()=>!window.tilemapWorkshop.grounded&&window.tilemapWorkshop.velocityY>=-220);
  await page.keyboard.down('Space');
  await page.waitForTimeout(70);
  assert.equal(await page.evaluate(()=>window.tilemapWorkshop.jumpsUsed),2,'a third airborne jump must be blocked');
  assert.ok(await page.evaluate(()=>window.tilemapWorkshop.velocityY)>-300,'a third press must not reset upward velocity');
  await page.keyboard.up('Space');
  await page.waitForFunction(()=>window.tilemapWorkshop.grounded&&window.tilemapWorkshop.movementPhase==='idle'&&window.tilemapWorkshop.jumpsUsed===0);
  await page.keyboard.down('Space');
  await page.waitForFunction(()=>!window.tilemapWorkshop.grounded&&window.tilemapWorkshop.jumpsUsed===1);
  await page.keyboard.up('Space');
  await page.waitForFunction(()=>window.tilemapWorkshop.grounded&&window.tilemapWorkshop.movementPhase==='idle');
  await page.keyboard.down('ArrowRight');
  await page.waitForFunction(()=>window.tilemapWorkshop.animation==='practice-walk'&&window.tilemapWorkshop.velocityX===220);
  const walkFrame=await page.evaluate(()=>window.tilemapWorkshop.frameIndex);
  await page.waitForFunction(previous=>window.tilemapWorkshop.frameIndex!==previous,walkFrame);
  await page.keyboard.down('Shift');
  await page.waitForFunction(()=>window.tilemapWorkshop.animation==='practice-run'&&window.tilemapWorkshop.velocityX===340);
  const runFrame=await page.evaluate(()=>window.tilemapWorkshop.frameIndex);
  await page.waitForFunction(previous=>window.tilemapWorkshop.frameIndex!==previous,runFrame);
  await page.keyboard.up('Shift');
  await page.waitForFunction(()=>window.tilemapWorkshop.animation==='practice-walk'&&window.tilemapWorkshop.velocityX===220);
  await page.keyboard.up('ArrowRight');
  await page.waitForFunction(()=>window.tilemapWorkshop.animation==='practice-idle'&&window.tilemapWorkshop.velocityX===0);
  for(const [sprint,animation] of [[false,'practice-walk'],[true,'practice-run']]) {
    await page.click('#reset-player');
    await page.waitForFunction(()=>window.tilemapWorkshop.grounded&&window.tilemapWorkshop.movementPhase==='idle');
    await page.keyboard.down('ArrowRight');
    if(sprint) await page.keyboard.down('Shift');
    await page.waitForFunction(expected=>window.tilemapWorkshop.animation===expected,animation);
    await page.keyboard.down('Space');
    await page.waitForFunction(()=>!window.tilemapWorkshop.grounded&&window.tilemapWorkshop.movementPhase==='rise');
    await page.waitForFunction(()=>window.tilemapWorkshop.movementPhase==='fall');
    await page.waitForFunction(()=>window.tilemapWorkshop.grounded&&window.tilemapWorkshop.movementPhase==='land');
    await page.waitForFunction(expected=>window.tilemapWorkshop.grounded&&window.tilemapWorkshop.animation===expected&&window.tilemapWorkshop.movementPhase===expected.slice(9),animation,{timeout:400});
    assert.ok(await page.evaluate(()=>window.tilemapWorkshop.landingElapsed)<110,'moving landing should promptly yield to the ground gait');
    const resumedFrame=await page.evaluate(()=>window.tilemapWorkshop.frameIndex);
    await page.waitForFunction(previous=>window.tilemapWorkshop.frameIndex!==previous,resumedFrame);
    await page.keyboard.up('Space');
    if(sprint) await page.keyboard.up('Shift');
    await page.keyboard.up('ArrowRight');
  }
  await page.click('#build-mode');
  await page.selectOption('#asset-pack',{index:1});
  await page.selectOption('#character',{index:1});
  await page.waitForFunction(()=>window.tilemapWorkshop?.ready&&document.querySelectorAll('#tile-palette .tile-option').length===16&&document.querySelectorAll('#phaser-stage canvas').length===1);

  await page.locator('#tile-palette .tile-option').nth(3).click();
  const canvas=page.locator('#phaser-stage canvas'); await canvas.scrollIntoViewIfNeeded(); const box=await canvas.boundingBox();
  const clickCell=async(x,y)=>canvas.click({position:{x:(x*48+24)*box.width/960,y:(y*48+24)*box.height/576}});
  await clickCell(4,5);
  await page.waitForFunction(()=>window.tilemapWorkshop.getSnapshot().placements.some(item=>item.x===4&&item.y===5&&item.frame===3&&item.solid),null,{timeout:1500}).catch(async error=>{
    const details=await page.evaluate(()=>({buildMode:window.tilemapWorkshop.buildMode,placement:window.tilemapWorkshop.getSnapshot().placements.filter(item=>item.x===4&&item.y===5),selected:document.querySelector('#tile-palette [aria-selected="true"]')?.dataset.tile,solid:document.querySelector('#solid-on-place').checked,tool:document.querySelector('#tool-grid [aria-pressed="true"]')?.dataset.tool,cameraPage:window.tilemapWorkshop.getSnapshot().cameraPage,canvas:document.querySelector('#phaser-stage canvas')?.getBoundingClientRect().toJSON()}));
    throw new Error(`Tile placement failed: ${JSON.stringify(details)}`,{cause:error});
  });
  await page.click('[data-tool="flip"]'); await clickCell(4,5);
  await page.waitForFunction(()=>window.tilemapWorkshop.getSnapshot().placements.some(item=>item.x===4&&item.y===5&&item.flipped));
  await page.click('[data-tool="collision"]'); await clickCell(4,5);
  await page.waitForFunction(()=>window.tilemapWorkshop.getSnapshot().placements.some(item=>item.x===4&&item.y===5&&!item.solid));
  await page.click('[data-tool="polygon"]'); await clickCell(10,2); await clickCell(12,2); await clickCell(11,3);
  await page.click('#finish-polygon');
  await page.waitForFunction(()=>window.tilemapWorkshop.getSnapshot().collisionPolygons.length===1);
  await page.click('[data-tool="spawn"]'); await clickCell(5,5);
  assert.deepEqual(await page.evaluate(()=>window.tilemapWorkshop.getSnapshot().spawn),{x:5,y:5});
  await page.click('#pan-right'); await page.click('#pan-right');
  assert.match(await page.locator('#camera-position').textContent(),/3 \/ 3/);
  await page.click('#pan-left'); await page.click('#pan-left');
  await page.fill('#template-name','Browser Test Run'); await page.click('#save-template');
  await page.waitForFunction(()=>document.querySelectorAll('#template-library option').length===2&&document.querySelector('#template-library').value);
  assert.equal(await page.locator('#load-template').isEnabled(),true);
  await page.click('#load-template'); await page.waitForFunction(()=>window.tilemapWorkshop?.ready&&window.tilemapWorkshop.getSnapshot().collisionPolygons.length===1);
  await page.click('#play-mode');
  await page.waitForFunction(()=>window.tilemapWorkshop&&!window.tilemapWorkshop.buildMode);
  assert.equal(await page.locator('#play-help').isVisible(),true);
  const before=await page.evaluate(()=>window.tilemapWorkshop.playerX);
  await page.keyboard.down('ArrowRight'); await page.waitForTimeout(450); await page.keyboard.up('ArrowRight');
  assert.ok(await page.evaluate(value=>window.tilemapWorkshop.playerX>value,before));
  await page.waitForFunction(()=>window.tilemapWorkshop.grounded&&window.tilemapWorkshop.movementPhase!=='land');
  await page.keyboard.down('Shift'); await page.keyboard.down('ArrowRight');
  await page.waitForFunction(()=>window.tilemapWorkshop.velocityX===340&&window.tilemapWorkshop.animation==='player-walk');
  await page.keyboard.up('ArrowRight'); await page.keyboard.up('Shift');
  await page.waitForFunction(()=>window.tilemapWorkshop.grounded);
  assert.ok(await page.evaluate(()=>window.tilemapWorkshop.playerY<528));
  assert.equal(await page.locator('#complete-module').isDisabled(),false);
  await page.click('#save-layout');
  await page.waitForFunction(()=>[...document.querySelectorAll('.action-toast')].some(item=>item.textContent.includes('checkpoint saved')));
  await page.click('#complete-module');
  await page.waitForFunction(()=>document.querySelector('#complete-module').textContent.includes('✓'));
  const learnerId=await page.evaluate(()=>localStorage.getItem('godot-forge-learner-id'));
  assert.equal((await (await fetch(`${baseUrl}/api/modules?learnerId=${learnerId}`)).json()).find(item=>item.slug==='parallax-tiling-map').completed,true);
  await page.reload(); await page.waitForFunction(()=>window.tilemapWorkshop?.ready);
  assert.deepEqual(await page.evaluate(()=>window.tilemapWorkshop.getSnapshot().spawn),{x:5,y:5});
  assert.equal(await page.evaluate(()=>window.tilemapWorkshop.getSnapshot().placements.find(item=>item.x===4&&item.y===5).flipped),true);
  assert.equal(await page.evaluate(()=>window.tilemapWorkshop.getSnapshot().collisionPolygons.length),1);
  await page.click('#languages [data-locale="zh"]');
  assert.match(await page.locator('#page-title').textContent(),/构建/);
  assert.match(await page.locator('#prompt-grid pre').first().textContent(),/用途：风格化概念图/);
  assert.match(await page.locator('#prompt-grid .prompt-card').nth(4).locator('.prompt-card-body > pre').textContent(),/腿和靴子/);
  assert.match(await page.locator('#prompt-grid .prompt-card').nth(5).locator('.prompt-card-body > pre').textContent(),/膝盖/);
  assert.match(await page.locator('#library-status').textContent(),/个素材包/);
  assert.match(await page.locator('#run-help').textContent(),/奔跑/);
  assert.match(await page.locator('#jump-help').textContent(),/二段跳/);
  assert.match(await page.locator('#tile-info-title').textContent(),/瓦片/);
  await page.click('#languages [data-locale="ms"]');
  assert.match(await page.locator('#prompt-grid pre').first().textContent(),/Kegunaan: konsep bergaya/);
  assert.match(await page.locator('#prompt-grid .prompt-card').nth(4).locator('.prompt-card-body > pre').textContent(),/Sudut kaki/);
  assert.match(await page.locator('#prompt-grid .prompt-card').nth(5).locator('.prompt-card-body > pre').textContent(),/lutut/);
  assert.match(await page.locator('#library-status').textContent(),/pek aset/);
  assert.match(await page.locator('#run-help').textContent(),/LARI/);
  assert.match(await page.locator('#jump-help').textContent(),/LOMPATAN KEDUA/);
  assert.match(await page.locator('#tile-info-title').textContent(),/Jubin/);
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  assert.deepEqual(dialogs,[]); assert.deepEqual(pageErrors,[]);
  console.log('PASS parallax editing, animated tile tooltips, templates, localized prompts, double jump, landing and resumed walk/run animation, Shift movement and checkpoint resume');
} finally {
  await browser?.close(); const exited=once(child,'exit'); child.kill('SIGTERM'); await exited;
}
